- lua/lib/utils.lua
fixes #10 . Damn those lua path matching are terrible
> fix path matching again

- lua/lib/git.lua
- lua/lib/populate.lua
- lua/lib/tree.lua
reduce calls to vim `system` which is blocking and takes a long time.
I tested on my home repo with deeply nested directories and saving doesn't block anymore !
closes #26
> optimize git with buffering

- lua/lib/git.lua
- lua/lib/populate.lua
- lua/lib/utils.lua
> fix lua path matching again

- README.md
- lua/lib/config.lua
- lua/lib/renderer.lua
Made folder icons configurable. It's related to #30.
> Add config option to change folder icons

- README.md
- doc/nvim-tree-lua.txt
- lua/lib/config.lua
- lua/lib/tree.lua
- lua/tree.lua
> add preview

- lua/lib/renderer.lua
Based on https://github.com/kyazdani42/nvim-web-devicons/pull/1/
**Before:**
--- 
<b>After</b>:
> Improve icon fetching logic

- lua/tree.lua
- plugin/tree.vim
> open tree on find

- lua/lib/renderer.lua
> fix space between icon and filename with special file

- lua/lib/lib.lua
- use setlocal for options instead of using nvim_win_set_option
- create a new window when there is only the tree window
- resize the tree when opening new files
fixes #67
> fix: always open new window and set window options locally

- lua/lib/populate.lua
> fix git highlight works without the icons

- README.md
- doc/nvim-tree-lua.txt
- lua/lib/config.lua
- lua/lib/renderer.lua
fixes #80 
I mean, it fixes my problem, but maybe some users still want to have an icon for symlinks? Feel free to close the issue if you consider
> Fallback to default icon for symlinks

- lua/lib/renderer.lua
> fix folder hl function with folder icon disabled

- lua/lib/fs.lua
This adds an option to rename a file/folder when doing copy or move.
> Add option to rename files when copying/moving. Closes #95.

- README.md
I just added a comma to the document.
Please check it, thanks.
> Corect the guide in the document

- lua/lib/lib.lua
- lua/tree.lua
> wrap refresh logic in vim.schedule callback

- lua/tree.lua
> fix issue with data race when opening with luatreefindfile

- README.md
- doc/nvim-tree-lua.txt
- lua/lib/config.lua
- lua/lib/lib.lua
- lua/nvim-tree.lua
As discussed, I made this into a default keymap & also updated the documentation. Thanks!
> Move dir_up functionality into lib and make '-' a default keymap for it

- lua/nvim-tree/lib.lua
> NvimTreeFindFile open a window in current tab

- README.md
- lua/nvim-tree/config.lua
- lua/nvim-tree/renderer.lua
Fixes #167
- New feature (non-breaking change which adds functionality)
> Add option for changing symlink opened folder.

- README.md
- doc/nvim-tree-lua.txt
- added git.deleted icon and highlight groups
- added symlink_open icon
> updated doc

- README.md
It just a tiny change.
I think newbie will put all setup code to their configuration file and do not realize why it was faulty.
> Fix setup in readme

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/git.lua
- lua/nvim-tree/populate.lua
> I found a better option

- lua/nvim-tree/fs.lua
> fix(file creation): avoid file overwrite and enable creating file on root node

- lua/nvim-tree.lua
- lua/nvim-tree/lib.lua
I've looked around and seen that asynchronous stuff was probably overkill for this plugin. I'm not sure if this might also improve performance so if people can test it i'd be much happy.
related: #172 
fixes #270
> chore: remove async to avoid unecessary complexity

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/colors.lua
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/utils.lua
- plugin/tree.vim
first attempt at integrating lsp diagnostics in the tree !
should fix #227
> feat: nvim lsp integration

- lua/nvim-tree/view.lua
> fix(view): Fix error thrown when trying to wipe buffer in autocmd window.

- lua/nvim-tree/renderer.lua
> chore(renderer): Simplify some of the git icon states.

- lua/nvim-tree/git.lua
> fix(git): Fix shell args on windows.

- lua/nvim-tree/renderer.lua
> fix(renderer): Ensure buffer is loaded.

- lua/nvim-tree/renderer.lua
> fix(renderer): Fix option check for highlight_opened_files

- lua/nvim-tree/lib.lua
> fix(lib): Fix the `tabnew` callback.

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/renderer.lua
This PR Is intended to improve highlighting options so it can suit most, if not all, of the need for tweaking file/folder highlights
> Improve highlight options

- lua/nvim-tree/lib.lua
> fix(lib): Refresh tree if it was opened before init.

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/config.lua
- lua/nvim-tree/renderer.lua
> add small arrows before folders

- lua/nvim-tree/view.lua
Disable cursorcolumn and colorcolumn
> Remove cursorcolumn and colorcolumn

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- plugin/tree.vim
Related to: https://github.com/kyazdani42/nvim-tree.lua/issues/468
> Add `NvimTreeResize size` to resize the NvimTree window

- lua/nvim-tree/fs.lua
Currently cutting files from one place to another leaves their buffers with the old name and saving that buffer will create a new file in the old location instead of saving to the new one. This change just renames the buffers the same way as if you renamed the file.
> Rename buffers on cut.

- README.md
- lua/nvim-tree/diagnostics.lua
If you don't like it, just close the pr :)
> feat(diagnostics): Support coc as diagnostic source(#555)

- lua/nvim-tree.lua
- lua/nvim-tree/view.lua
This PR enables opening the tree fullscreen when editing a directory. It also enables opening the tree fullscreen on enter with `vim DIR` or `vim`
Related: #238 #436 #200 #214 #248 #131 #188 
@sindrets i'll leave this open for a week or so, i think it should work, but i need people to test it before i merge it.
> feat: open tree on directory

- lua/nvim-tree.lua
> fix: lsp_diagnostics switch reversed.

- lua/nvim-tree/diagnostics.lua
See: https://github.com/neovim/neovim/issues/14090#issuecomment-979424077
> chore(diagnostics): follow upstreams autocommand's rename

- lua/nvim-tree/lib.lua
> fix: NvimTree does not open the file when it is open standalone

- doc/nvim-tree-lua.txt
In PR #805, not notice there are two spaces in document.
> delete extra space in doc

- lua/nvim-tree/view.lua
> feat: set up view width/height with function

- doc/nvim-tree-lua.txt
> fix: lua dsl syntax error in doc

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/populate.lua
See #856 
Not sure if the naming is suitable, would appreciate other suggestions
> feat: add exclude filter list

- lua/nvim-tree/utils.lua
A better way to raise warnings without VimL hacks.
> A more modern way to raise warning message

- lua/nvim-tree/colors.lua
- lua/nvim-tree/renderer/init.lua
I find there are something wrong when getting highlight from current colorscheme. On the right way hlID should be passed to synIDtrans() function first. :)
> fix: colors setup highlight

- lua/nvim-tree.lua
> feat(preview): enhanced preview to toggle folder

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/lib.lua
> Add a config option to use :cd instead of :lcd

- lua/nvim-tree/git/runner.lua
Fix hiding files according to .gitignore
Fix #910 
Fix #895 
Fix #845 
Maybe related to #578
> Fix git icons on files and folders in subfolders

- lua/nvim-tree/lib.lua
Fix broken functionality from https://github.com/kyazdani42/nvim-tree.lua/commit/8c4fd519b6f10c3a317af64a56060da87a1a1ea4
> fix: close_node

- lua/nvim-tree/actions/remove-file.lua
> fix: Delete a file as an open buffer

- lua/nvim-tree/actions/find-file.lua
fixes #969
~might fix #970~ neovim bug
> fix: find file waits for git to finish

- lua/nvim-tree/actions/remove-file.lua
- lua/nvim-tree/utils.lua
remove-file [before](https://gyazo.com/de97a8661cc438669381b2790cdb309f),
[example](https://gyazo.com/97f0a8ab23a3dfeeeb9c1f30394d295d) with [nvim-notify](https://github.com/rcarriga/nvim-notify)
> fix: close windows properly

- lua/nvim-tree/git/runner.lua
> fix: do not match ignored when not showing untracked files

- lua/nvim-tree/actions/init.lua
> #973 copy action_cb for view.mappings.custom_only

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/init.lua
- plugin/nvim-tree-startup.lua
> feat: Add a new keybinding "W" to collapse the whole tree

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/view.lua
[Before](https://asciinema.org/a/kUQ5jCy8oujceqTtZFye5tAym)
[After](https://asciinema.org/a/D4jZgcfvyysKBmtqfcquBtadj)
Please let me know if there's anything I haven't considered in this PR
> fix: add config for preserving window proportions on open file

- lua/nvim-tree/actions/movements.lua
- lua/nvim-tree/lib.lua
Rewrote `find_git_item`
Repurposed `get_node_at_line` as `get_nodes_by_line`
> #972 bug: prev_git_item with hijack_cursor selects icon instead of previous file

- doc/nvim-tree-lua.txt
> doc: remove unused g:

- lua/nvim-tree/actions/search-node.lua
> fix: changed search_node action to determine correct index

- lua/nvim-tree/utils.lua
TIL vim.inspect
nvim has a lot of useful convenience extensions for lua. Thanks for letting me know.
> remove table_tostring

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/copy-paste.lua
- Added logs to copy-paste
- Added more error and sanity checks to copy-paste
The diffs shown in the PR are pretty difficult to read. Best to checkout and `git diff -w `.
do_copy - many changes
do_single_paste, do_paste - some changes
do_cut - minimal changes
> #1064 add copy_paste logging and more error copy-paste error handling

- lua/nvim-tree/explorer/node-builders.lua
Only issue might be performance, however we are already scanning directories...
> #504 determine whether symlinked directories are empty when building

- README.md
Remove markdown comment from defaults code block.
> markdown comments displayed in text block; replace with lua comments

- lua/nvim-tree/actions/collapse-all.lua
> 1127 collapse exit early if nvim-tree not loaded

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
closes #372
The name is a bit ugly however I don't want to change the existing `open_on_setup` option and break people.
> add open_on_setup_file option

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/legacy.lua
- lua/nvim-tree/renderer/init.lua
- lua/nvim-tree/renderer/padding.lua
> add view.indent_markers

- doc/nvim-tree-lua.txt
> #1146 clarify filters.exclude and toggle actions

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/change-dir.lua
> add actions.change_dir.restrict_above_cwd

- doc/nvim-tree-lua.txt
closes #1169 
We could autogenerate this from comments somehow, but that is complex and provides little value.
> #1169 document event payloads

- README.md
> doc: add missing space in readme

- lua/nvim-tree.lua
- lua/nvim-tree/legacy.lua
> 1210 silent migrate more options

- lua/nvim-tree/actions/change-dir.lua
- lua/nvim-tree/actions/collapse-all.lua
- lua/nvim-tree/actions/movements.lua
- lua/nvim-tree/actions/reloaders.lua
- lua/nvim-tree/actions/toggles.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/renderer/init.lua
> chore(diagnostics): move updates to renderer

- lua/nvim-tree/actions/movements.lua
> fix(close-node): do not close parent when current node is open

- lua/nvim-tree/diagnostics.lua
This was simpler than I expected.
> #1216 respond to CocDiagnosticChange

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/renderer/init.lua
- lua/nvim-tree/view.lua
Will adapt the view size based on the longest line.
fixes #865
> feat(resize): add ability to grow and shrink the tree when drawing

- README.md
Dealing with issues like #1318 is becoming very difficult.
> doc: add help wanted and contributing

- lua/nvim-tree.lua
- lua/nvim-tree/view.lua
> prevent open buffer on NvimTree window when quite_on_open is true

- lua/nvim-tree/actions/trash.lua
closes #1366 
Forgot to raise this PR...
> fix(#1366): warn when trash cmd missing

- lua/nvim-tree/git/init.lua
I'm glad I added profiling for git utils... we call get_toplevel all the time!
get_project_root stopped caching `cwd_to_project_root`; add to that cache.
Check that cwd exists to deal with badly behaved shells e.g. https://github.com/kyazdani42/nvim-tree.lua/issues/549#issuecomment-1186577715
> chore(git): get_project_root cache cwd_to_project_root after checking existence

- lua/nvim-tree/keymap.lua
Resolves kyazdani42/nvim-tree.lua#1514
> Fix inverted git navigation keymaps

- lua/nvim-tree/explorer/reload.lua
> fix(#1518): sort_by=modification_time not reordering on refresh.

- lua/nvim-tree/view.lua
> fix(#1529): ensure tree window exists before closing

- lua/nvim-tree/view.lua
> fix(view): Fix view.width overriding view.float.open_win_config

- lua/nvim-tree/explorer/node-builders.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/utils.lua
> fix(#1555): incorrect exe highlight in Windows filesystem from WSL

- lua/nvim-tree/actions/fs/remove-file.lua
> fix(view): Fix closing nvim-tree float when file is removed

- lua/nvim-tree/actions/node/open-file.lua
fixes #1564 
@clatisus please test.
> fix(#1564): reset &bufhidden when opening an existing (maybe previewed) buffer

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
> chore(#1593): add :NvimTreeFindFile! doc and add bang to :NvimTreeFindFileToggle

- lua/nvim-tree/actions/fs/create-file.lua
- lua/nvim-tree/explorer/watch.lua
> fix(#1615): focus created file when command line prompt requires confirmation

- lua/nvim-tree/view.lua
> fix: invalid window ID on colorscheme #1712

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
Reverted earlier following https://github.com/nvim-tree/nvim-tree.lua/commit/623cecb809c6ec35b8ddd47a57732ee2c57446f5#commitcomment-93256546
Fixed toggle case.
> 1815 telescope update focused file regression attempt 2

- lua/nvim-tree/actions/finders/find-file.lua
resolves #1833
Fix tested by users
> fix(#1833): do not find file when view is not visible on the current tab

- .github/dependabot.yml
- .github/workflows/release-please.yml
> ci: add release-please workflow

- .github/workflows/release-please.yml
Release type was wrong as well as package name.
> ci: fix release-please workflow

- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/watcher.lua
> fix(#1822): test directory capable of watching before presenting it

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
> feat(event): add autocommands NvimTreeRequired, NvimTreeSetup

- lua/nvim-tree/renderer/components/git.lua
fixes #1923 
There aren't any similar cases, although we will need to do the same when implementing #1510
> fix(#1923): handle empty git icons

- lua/nvim-tree/explorer/explore.lua
> fix(#1831): remove instrumentation

- lua/nvim-tree/renderer/components/git.lua
> 1923 skip empty git icons

- lua/nvim-tree/lib.lua
> fix(#1993): always fire TreeOpen event

- lua/nvim-tree/actions/node/open-file.lua
> fix(#2003): obey user split command for modified buffers when hidden not set

- lua/nvim-tree/actions/fs/copy-paste.lua
Hi there, just noticed one of the notification messages reads wrong, so this is a tiny PR to fix it.
> Fix typo on clipboard notify

- doc/nvim-tree-lua.txt
- lua/nvim-tree/api.lua
- lua/nvim-tree/keymap-legacy.lua
- lua/nvim-tree/keymap.lua
- scripts/update-help.sh
Add `api.config.mappings.default_on_attach` and documentation.
Tidy function definitions, fix update_help bug with duplicate opts.
> feat(api): add api.config.mappings.default_on_attach

- lua/nvim-tree.lua
> fix(#2081): find-file change_root ignore inexistent files

- lua/nvim-tree/api.lua
@hinell I would be most grateful for your review / test.
> fix(#1858): deprecation warning for config.mappings.active and default

- lua/nvim-tree.lua
> fix(#2078): NvimTreeFindFile focus tree

- lua/nvim-tree/events.lua
- lua/nvim-tree/lib.lua
> fix(#2114): remove deprecated non-API

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
> feat(#1669): remove deprecated open_on_setup mechanisms

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/legacy.lua
- lua/nvim-tree/view.lua
> feat(#1808): deprecate hide_root_folder

- lua/nvim-tree/api.lua
> fix(#2139): wrap function not passing arguments to API calls.

- lua/nvim-tree/keymap-legacy.lua
Is it time @gegoune ?
After some time we can disable: #2144
> feat: deprecate view.mappings.list

- doc/nvim-tree-lua.txt
- lua/nvim-tree/api.lua
> feat(api): add tree.is_visible, tree.is_tree_buf

- .github/ISSUE_TEMPLATE/nvt-min.lua
#2154 highlighted the need for this.
> test: disable netrw for clean room

- lua/nvim-tree/actions/node/open-file.lua
context: https://github.com/nvim-tree/nvim-tree.lua/pull/2209#issuecomment-1546794213
> fix(#2191): edit: disregard floating windows

- README.md
- doc/nvim-tree-lua.txt
> docs: add on_attach to quickstart

- lua/nvim-tree/actions/finders/find-file.lua
- lua/nvim-tree/explorer/reload.lua
fixes #2293
https://github.com/nvim-tree/nvim-tree.lua/issues/1731 https://github.com/nvim-tree/nvim-tree.lua/issues/1723 https://github.com/nvim-tree/nvim-tree.lua/issues/1716 cases have been successfully tested.
> fix(#2293): remove unnecessary git status during find file

- lua/nvim-tree/explorer/node.lua
> fix(#2301): do not show git status on grouped dirs when show_on_open_dirs

- doc/nvim-tree-lua.txt
> docs: sort.sort_folders_first -> sort.folders_first

- doc/nvim-tree-lua.txt
- lua/nvim-tree/log.lua
fixes #2162
I thought I did this a long time ago...
> chore: use stdpath "log" rather than "cache"

- lua/nvim-tree/git/runner.lua
> fix(#2386): kill git zombies

- doc/nvim-tree-lua.txt
Just some minor typos/oversights.
> docs: add missing quotes

- lua/nvim-tree.lua
Also added `{ title = "NvimTree" }` for notification plugins that support it.
> fix: schedule notifications to avoid UI freeze on startup

- lua/nvim-tree/api.lua
Closes #2495.
This should be sufficient to handle all cases.
> fix(#2495): skip action if node == nil

- lua/nvim-tree/actions/node/open-file.lua
> feat(#2530): keep alt filename on node.open.replace_tree_buffer

- README.md
> docs: update quick start example

- .github/workflows/release-please.yml
- release-please-config.json
> ci: configure release-please

- lua/nvim-tree/api.lua
> fix(#2609): help toggle

- README.md
> chore: release 1.0.0

- lua/nvim-tree/explorer/explore.lua
fixes #2868
fixes #2866 
supersedes #2867
> fix(#2868): windows: do not visit unenumerable directories such as Application Data

- lua/nvim-tree/actions/moves/parent.lua
> fix(#2928): nil explorer in parent move action

- lua/nvim-tree/explorer/init.lua
> fix(#2930): empty groups expanded on reload

- lua/nvim-tree/explorer/init.lua
> fix(#2972): error on :colorscheme

- lua/nvim-tree/appearance/hi-test.lua
- lua/nvim-tree/help.lua
- lua/nvim-tree/renderer/components/full-name.lua
- lua/nvim-tree/renderer/init.lua
> fix(#3059): test for presence of new 0.11 API vim.hl.range

- lua/nvim-tree/utils.lua
Like #3118 but without the broken commit history. Works for CMD/Powershell.
> fix(#3117): windows: change file/dir case

- lua/nvim-tree/renderer/decorator/init.lua
> fix(#3134): setting one glyph to "" no longer disables others

- .hooks/pre-commit.sh
- scripts/doc-comments.sh
- scripts/help-update.sh
- scripts/luals-check.sh
context: https://github.com/nvim-tree/nvim-tree.lua/pull/3140#discussion_r2117929147
> chore: use portable shebangs consistently

- lua/nvim-tree/explorer/live-filter.lua
> fix(#3172): live filter exception
