- README.md
- doc/nvim-tree-lua.txt
- doc/tags
- lua/lib/config.lua
- lua/lib/winutils.lua
> Feature: add option for user keybindings

- lua/lib/config.lua
I just copied the default settings from the README and was very confused that `d` would rename a file...
> Bugfix: delete key would rename if set

- lua/lib/colors.lua
- lua/lib/config.lua
- lua/lib/winutils.lua
- lua/tree.lua
- plugin/tree.vim
Fixes #8 ! (not sure about the part where i get the colors from the HL groups (could not test), but the rest should work fine)
> Add colorscheme update and add filetype to buffer.

- lua/tree.lua
- plugin/tree.vim
@kyazdani42 I tried the most recent change to master and realised it wasn't working. The last change you made was the correct logic but it was in a function that only ran on `VimEnter` and had `auto_open` set to 1. The line is [here](https://github.com/Akin909/nvim-tree.lua/blob/5fcbc21edb08c77b3afd938958ad70178ee74d1f/plugin/tree.vim#L19).
I moved the logic you added into a separate function and call it on `BufEnter` that way when you change buffer the Lua Tree updates to the new root dir.
Lemme know what you think. I added it as an option rather than the default, although I think maybe it should be default behaviour
> Add config option to follow buffer's directory

- lua/lib/fs.lua
- lua/lib/populate.lua
- refreshing delete from entries before adding new entries to avoid
conflicts with indexes
- delete is synchronous because on large folders it was not recursing
properly thus causing errors and not deleting content.
fixes #25
> fix: fs and refresh bugs

- README.md
- doc/nvim-tree-lua.txt
- lua/lib/lib.lua
* Option for disabling keybindings by plugin. When disabled, all bindings need to be created by the users on their own accord.
> Add option for disabling bindings

- README.md
- doc/nvim-tree-lua.txt
- doc/tags
- lua/lib/colors.lua
- lua/lib/renderer.lua
@Akin909 can you review this works as expected for you ? Or tell me if you'd prefer something else.
(add `let g:lua_tree_indent_markers = 1` to your init.vim)
fixes #42
> add indent markers

- README.md
- doc/nvim-tree-lua.txt
- lua/lib/config.lua
- lua/lib/lib.lua
- lua/lib/populate.lua
- lua/tree.lua
This is another feature that I mentioned in https://github.com/kyazdani42/nvim-tree.lua/issues/51
> Add mapping for toggling ignored folders visibility.

- lua/lib/populate.lua
@Akin909 could you try this to see if it solves #50 ?
closes #50
> fix: remove goto statement to match neovim lua version

- README.md
- doc/nvim-tree-lua.txt
- lua/lib/config.lua
- lua/lib/fs.lua
- lua/lib/lib.lua
- lua/tree.lua
- plugin/tree.vim
This PR adds cut, copy and paste functionality that I mentioned in issue https://github.com/kyazdani42/nvim-tree.lua/issues/51
Note that I don't have much experience with Lua, so do as detailed review as possible.
> Add cut,copy and paste functionality.

- README.md
- doc/nvim-tree-lua.txt
- lua/lib/config.lua
- lua/lib/lib.lua
- lua/tree.lua
This is one more feature request that i mentioned in #51 .
It's just a simple search for any git icon from current line. This is how I implemented it for defx, and nerdtree git plugin does the same. No one complained so far :)
> Add mappings for jumping to previous or next git item.

- lua/lib/lib.lua
- lua/tree.lua
This is a fix for issue that i mentioned here https://github.com/kyazdani42/nvim-tree.lua/issues/58#issuecomment-663120555.
I use this command a lot, and I like to have it consistent.
> Always focus tree when finding file.

- lua/lib/config.lua
- lua/lib/renderer.lua
```vim
let g:lua_tree_icons = {
\ 'default': '  ',
\}
```
Closes https://github.com/kyazdani42/nvim-tree.lua/issues/45
> Icons: allow setting a string as file icon

- README.md
- doc/nvim-tree-lua.txt
- doc/tags
- lua/lib/colors.lua
- lua/lib/config.lua
- lua/lib/populate.lua
- lua/lib/renderer.lua
fixes #65 
You can now set `g:lua_tree_git_hl = 1` to color file from their git attributes.
TODO: update the pictures
> refacto display and add LuaTreeFolderDirty group

- lua/lib/git.lua
- plugin/tree.vim
This is a small improvement to git status.
For example, when you have two files in some existing folder, and you stage both files, directory git status is still shown as dirty, but I think it should show as staged, since everything in it is staged.
For the `-u` part, this is useful for new files and folders added. status with `-u` will return list of new files that are part of new folder.
So if you have a new folder and file named `myfolder/myfile.vim`, status without `-u` will return only `myfolder/`, where `-u` will return `myfolder/myfile.vim`.
Also, I introduced refreshing the tree when fugitive changes the git status of some file.
> Inherit git status from nested files on directory.

- lua/tree.lua
When `let g:lua_tree_follow` is `1` then on `BufEnter` the cursor is placed on the current file. This is similar to how `LuaTreeFindFile` works. But if you have this setting set as `1` and do `LuaTreeToggle` the current file is not selected. The cursor is placed on the first item. If you leave the window and return `BufEnter` is triggered and cursor is placed on the file.
This is really helpful if you work in a nested repository since opening the tree to the first item is not very useful as it means you have to search every time. You could use the find file command but this doesn't toggle the tree so a user would have to implement some work around.
If a user has set `g:lua_tree_follow` to `1` and they use `LuaTreeToggle` the tree opens with the current file already in focus.
I changed the …
> Show selected file on toggling nvim tree

- README.md
- doc/nvim-tree-lua.txt
- lua/lib/colors.lua
- lua/lib/config.lua
- lua/lib/lib.lua
- lua/lib/renderer.lua
These are the improvements I mentioned in https://github.com/kyazdani42/nvim-tree.lua/issues/76.
For multiple keys for single action, I added `o` as part of default for open action. I believe a lot of people are used to that mapping, especially if they come from nerdtree. If you disagree we can remove it.
For root folder name, I wasn't sure what is the best way to introduce it, so again, I copied nerdtree :)
I didn't provide an option to disable it, because that would introduce a lot more checks. If you think we need to have it, i'll introduce it.
Here's the screenshot how it looks for me:
> Improvements

- lua/lib/colors.lua
- lua/lib/config.lua
- lua/lib/renderer.lua
- lua/lib/utils.lua
Git deleted state (` D`) wasn't handled, so it threw an error, because fallback wasn't set properly.
This PR introduces handling the delete state, and properly falling back to default dirty state if not found in the table. Feel free to adjust the icon, I wasn't sure what to put.
> Handle git deleted state.

- README.md
- doc/nvim-tree-lua.txt
Replace `g:lua_tree_size` with `g:lua_tree_width` in document according to https://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/lib/lib.lua#L19.
Please check, thanks.
> Update document for g:lua_tree_width

- lua/lib/git.lua
fixes #28 #102  ! Finally, we needed to wrap the path in double quotes instead of trying to escape the characters manually which caused issues with the `system` command.
> fix cd to path with symbols need "

- README.md
Hey, I've just discovered the plugin and while it's pretty awesome so far, I found a little bug in the README vim setup snippet which results in syntax error after being loaded by neovim. I think you forgot to put a `\` before the last `}` to close the `g:lua_tree_bindings` dictionary.
Hope this helps others!
> Fix setup snippet in README.md

- lua/lib/lib.lua
This is another take on small enhancement that allows window width resize if g.lua_tree_width_allow_resize is set to true.
> feat: allow window width resize

- lua/lib/lib.lua
> fix: `Previewing a file with g:lua_tree_quit_on_open closes the file browser`

- lua/lib/git.lua
closes #28 .
This is a monkey patch and does not resolve the underlying issue which might just be path matching. It will be properly resolved in v2
> fix git root for v1 (monkeypatch)

- lua/lib/renderer.lua
This PR should fix https://github.com/kyazdani42/nvim-tree.lua/issues/134
tree.winnr is a function that returns winnr of luatree.
So we should use tree.winnr() instead of tree.winnr.
> fix tree winnr

- README.md
- doc/nvim-tree-lua.txt
- lua/lib/config.lua
- lua/lib/lib.lua
- lua/tree.lua
Introduce `close_node` action and keybinding <kbd>Backspace</kbd> to close current opened directory, or parent.
Fixes #105 
This works great for h/j/k/l movement:
```vim
let g:lua_tree_bindings = {
\ 'close_node': 'h',
\ 'edit': 'l',
\ }
```
> Add close_node action to close parent directory

- lua/lib/populate.lua
I've been getting some errors on startup due to link_to being nil, so I figured I should add a nil check. Let me know if you have any suggestions.
> Add nil check for link_to

- lua/tree.lua
with `let g:lua_tree_auto_close = 1`, while closing the tree when it's the last window,
neovim ask the user: "Press ENTER or type command to continue"
this patch should fixup the problem
> feat: auto close: avoid force user to press Enter key to exit

- lua/lib/populate.lua
For example, I don't want to display `*.pyc` files in python project. Now I can achieve it by adding `*.pyc` to the `g:lua_tree_ignore`.
This is a simple but small change implementation.
> feat: g:lua_tree_ignore support *.extension

- README.md
- doc/nvim-tree-lua.txt
It's actually `lua_tree_width_allow_resize` in the code.
> Fix lua_tree_allow_resize variable name in docs

- lua/lib/renderer.lua
This PR fixes the inconsistency in how we calculate the length of folder icon and file icon. 
Length of folder icon was calculated after a space is appended, and length of file icon was calculated without any space appended.
It is fixed by adding one after `#icon` for file icons.
This PR should fix #160
> fix file icon length

- plugin/tree.vim
rename `lua_tree_auto_close` ->  `nvim_tree_auto_close`
rename `lua_tree_tab_open ` -> `nvim_tree_tab_open`
and fix the issue that the tree can not auto close :D
> renaming: lua-tree -> nvim-tree

- lua/nvim-tree.lua
Just a suggestion. I like to use the '-' key to open the tree, then inside the tree, to use '-' to quickly navigate up through the directory structure. I couldn't figure out how to do that second part without adding a function to the main package. If there's a better way to do this, I'd love to hear it. Thanks
> Add dir_up function to expose navigating up one directory

- lua/lib/lib.lua
- lua/nvim-tree.lua
Hi, this is for your consideration. If you don't buy my arguments, I understand.
I think this addresses the concern in issue #171 and maybe a few others
Rationale: I prefer somewhat different semantics than the existing code when opening a node, as described below. To me, this is more intuitive and more or less follows what NERD_Tree does (as I recall -- been a while since I used it). For example, some things that are better in my view with this approach:
* If I start nvim-tree from the leftmost window while that buffer is modified, the default edit command would fail to open the file. With this approach, if the window contains a modified buffer, it will split automatically.
* if I open nvim-tree from the rightmost window, when I open a node it will replace my leftmost buffer, which i …
> Execute action in target window if possible (fixes #171)

- lua/lib/lib.lua
- Honor `hidden` setting when deciding whether to split window
- Remove unused `check_and_open_split()`
Refer to [this comment](https://github.com/kyazdani42/nvim-tree.lua/pull/174#issuecomment-761575598)
> Honor the 'hidden' option when deciding whether to split the target window

- lua/lib/git.lua
Some git use cases, specifically, in my case, where $HOME is a git worktree
with a bare git repo somewhere else, really get bogged down if you do `git
status -u`. It was making the plugin unusable when `GIT_WORK_TREE=$HOME`
environment variable is set as such. This overcomes that issue.
> Don't do `git status -u` if repo is configured not to show untracked files

- lua/lib/lib.lua
I have a weird case where I need to open a file with `$` in its filename. ex. `$layout.svelte`, if we don't escape it, it will open a buffer with `.svelte` as its filename instead of `$layout.svelte`
> fix: escape filename before opening it

- lua/lib/fs.lua
Changes the behaviour of renaming a file or folder. This will remove the current filename from the absolute path, so it's not necessary to backspace the current name before typing in the new name.
> change behaviour of rename

- lua/lib/colors.lua
- lua/nvim-tree.lua
- plugin/tree.vim
This solves #193 as I posed.
I try to avoid `colors.setup()` being deferred by moving it into `plugin/tree.vim`.
> Avoid intro screen cleared

- lua/lib/populate.lua
I noticed that trying to inspect if a directory was empty, it would error when the user did not have read permissions. This is not a situation that comes up too often, but obviously should be fixed anyway.
The error was coming from the fact that `luv.fs_scandir()` returns `nil` if the specified directory is not readable by the user. `luv.fs_scandir_next()` then assumes that the provided handler is of type `uv_req`, hense the error.
> Fix error when attempting to read from a restricted directory

- README.md
- doc/nvim-tree-lua.txt
- lua/lib/config.lua
- lua/lib/fs.lua
- lua/lib/lib.lua
- lua/nvim-tree.lua
- add <C-r> binding to omit the filename on rename (option is
full_rename).
- call `silent! write!` on rename to avoid the `overwrite existing file`
error when saving the buffer.
> feat/fix: add rename cmd, fix rename error

- README.md
- doc/nvim-tree-lua.txt
There is some wrong example on `g:nvim_tree_icons` dictionary value for folder `empty` & `empty_open`.
I guess that example is for lua.
> Fix: wrong dictionary format example for empty & empty_open on doc

- lua/nvim-tree/lib.lua
g:nvim_tree_git_hl is not disabling Git status reloading even when g:nvim_tree_show_icons.git is 0.
> Fix g:nvim_tree_git_hl is not disabling Git status reloading

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/fs.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/populate.lua
- lua/nvim-tree/renderer.lua
Fixes #191.
This adds an option `g:nvim_tree_group_empty` (disabled by default) that compacts dirs that only contain 1 dir / symlink dir, into one node in the file tree.
> feat: Option for grouping empty directories

- lua/nvim-tree/lib.lua
This makes it so that the file tree buffer is only created if a previously created buffer cannot be found.
- What does this solve?
- When the tree window is closed, the tree buffer is wiped. When the tree window is opened again, the tree buffer is recreated and the state of the previous tree is lost. All previously opened folders are now closed.
> feat: preserve the file tree buffer

- lua/nvim-tree/populate.lua
If you have build/ or /build in your .gitignore,
the ls-files command will print directories as build/.
> Gitignore: fix ignoring directories

- lua/nvim-tree/lib.lua
Find file on windows doesn't work when using hard coded path separator '/'. 
Updated `set_tree_index_and_redraw` to use `utils.path_separator`.
> Use platform path separator when setting tree index.

- .editorconfig
- doc/nvim-tree-lua.txt
- lua/nvim-tree/events.lua
- lua/nvim-tree/fs.lua
Opening a WIP draft PR just to get a discussion going.
I think it'd be really neat being able to hook into the different actions nvim-tree does. For example - when renaming a node I'd like to inform my LSP client that a rename just happened:
```lua
local events = require'nvim-tree.events'
local typescript_ls = require'lsp.clients.typescript'
events.register_callback('renamed', function (old_fname, new_fname)
typescript_ls.rename_file(old_fname, new_fname)
end)
```
I went with quite a vanilla event system where any amount of callbacks can be registered for any given event name.
> add event API

- lua/nvim-tree.lua
- lua/nvim-tree/config.lua
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/populate.lua
- lua/nvim-tree/renderer.lua
- lua/nvim-tree/view.lua
buffer / window handling has been put in its own separate module called 'view'.
buffer will never be destroyed and is created on init. It simplifies the code and allows for easier extensibility.
also simply fix #219 by issuing a `wincmd =` to resize windows on open
> chore: rewrite buffer/window handling into view file

- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/utils.lua
When at least one root file with lsp diagnostics problems is present and at least one  folder with more then 0 child nodes is expanded - NvimTree would  throw an error:
```
Error executing vim.schedule lua callback: ...lua/nvim-tree/diagnostics.lua:23: Column value outside range
```
This happens because:
* `bufnr` was taken from the `lib.Tree` instead of `view.View`.
* wrong `linenr` being passed  to `highlight_node` from `find_node` where every step of recursion would produce + 1 index offset for each child node without highlight.
> fix (lsp diagnostics highlight): find_node index, bufnr

- lua/nvim-tree/view.lua
Fixes #301.
Calling `vnew` creates a new empty buffer every time the tree opens. The window then changes to the correct buffer only a couple lines later, leaving the unused, unneeded, empty buffer behind.
> fix(view): Don't create a new empty buffer on every open.

- doc/nvim-tree-lua.txt
- lua/nvim-tree/events.lua
- lua/nvim-tree/lib.lua
Adds a `ready` event that is dispatched after NvimTree has been initialized.
Related to discussion in #280.
> feat(events): Add a `ready` event.

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/config.lua
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/lib.lua
- plugin/tree.vim
This makes the diagnostic signs in the tree more responsive by using the `LspDiagnosticsChanged` auto command event rather than `BufWritePost`, as well as updating diagnostics where it made sense (`unroll_dir`, `refresh`). It also adds configurable icons for the four types of diagnostics.
```lua
lsp = {
hint = "",
info = "",
warning = "",
error = "",
},
```
I also fixed an error where diagnostics were sorted by highest severity. As far as I can tell, the severity property works kind of backwards in that severity 1 is `error`, and severity 4 is `hint`. This seemed consistent across all the language servers I tested.
> feat(diagnostics): More responsive and configurable diagnostics signs.

- lua/nvim-tree/lib.lua
- lua/nvim-tree/view.lua
- plugin/tree.vim
Fixes #296.
This makes the tree able to recover when the tree buffer gets deleted or wiped. It also tackles scenarios where the NvimTree buffer already exists before initialization, as a result of i.e. a session being loaded. This is what I believe is the root of the problems described in 296.
> fix(view): Recreate tree buffer if deleted, and handle scenario where buffer already exists.

- lua/nvim-tree.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/renderer.lua
- lua/nvim-tree/view.lua
handle many windows by loading them in tabpages and use an util function to load the correct window.
Also fixes all the segmentation fault issues, not sure why this happened, maybe because of window operations on a different tabpage !
fixes #311 
fixes #233 
fixes #239
fixes #223
> fix: handle new tabs properly

- lua/nvim-tree/lib.lua
Ensure diagnostics signs are updated when folders are opened/closed so that signs won't be misaligned.
> fix(diagnostics): Update lsp diagnostics signs when opening/closing folders.

- lua/nvim-tree/view.lua
This a small PR to add the ability to highlight the statusline differently in the nvim-tree buffer using `NvimTreeStatusLine` and `NvimTreeStatusLineNC` similar to the other `winhighlight` for other highlight groups.
NOTE: I converted the highlights to a table and concat them for readability sake so the line isn't so long and hard to read. Happy to change it back if this is undesirable 🤷🏿‍♂️
> feat: add statusline winhighlight to explorer tree

- lua/nvim-tree/view.lua
Setting the buffer name in `setup` might fail because `_wipe_rogue_buffer` is not synchronous:
https://github.com/kyazdani42/nvim-tree.lua/blob/983963779d6696c5b6b4aa14f874d85f00941b4e/lua/nvim-tree/view.lua#L119-L120
Rename the rogue buffer synchronously so that this doesn't happen.
> fix(view): Rename rogue buffer.

- lua/nvim-tree/populate.lua
Fixes #324.
Currently changing the link target of a symlink is not reflected in the tree, unless both the previous target and the new target are directories. This PR makes it so symlink nodes are recreated if they have been modified.
> fix: Update symlinks if they have been modified.

- lua/nvim-tree/colors.lua
This sets some default highlight links for the new `NvimTreeStatusLine` highlight groups so that vim doesn't fill the statusline with carrots.
Example with minimal rc:
Before:
After:
fixes #332
> chore(colors): Set highlight links for NvimTreeStatusLine

- lua/nvim-tree/populate.lua
- lua/nvim-tree/utils.lua
Currently nodes don't always appear in conventional order in the file tree, and they are sometimes inserted in the wrong position when multiple nodes are added. This is a limitation of how insertion of new nodes is currently implemented. Further, symlinks are "sorted" as a separate group as opposed to how it is conventionally done: treating symlinks as the type of file/folder it points to. I.e a symlink pointing to a folder should be sorted alongside other folders.
Proposed solution: sort folders when new nodes are added. This is reasonable and does not have much notable impact on performance with my current implementation. Lua's `table.sort` is backed by an unstable quick sort algorithm, so I opted to instead implement a stable merge sort. Running some tests i measured a ~6.2ms runtime …
> feat: Sort nodes sensibly

- lua/nvim-tree/git.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/populate.lua
- lua/nvim-tree/renderer.lua
After using my previous gitignore implementation for a while I discovered that it has some problems. I.e. it does not list ignored files unless the files' parent directory is checked in to git. But after reading through some git man-pages, I found out that we can vastly simplify the implementation by adding the `ignored=matching` option to the `git status` command. This is just a lot more elegant overall, as then setting the ignore status is done exactly the same way we set all the other git statuses.
The `gitignore_map` is still needed for the `g:nvim_tree_gitignore` feature, but I'm now just constructing it as part of the `update_root_status` function.
> fix(git): Fix the gitignore implementation.

- lua/nvim-tree/fs.lua
I was a little bothered that the filesystem actions needed you to press `<cr>` after every command. When overwriting files, it's `y<cr>` or `r<cr>` or `n<cr>`. You get it. I thought it would be a lot nicer to have the actions execute instantly, so I made those changes.
I've also made some minor changes to the UX, just to simplify the experience. I didn't think there needed to be text saying a file was created, since you just told the plugin to do it, and you can see it in the tree view. Same with removing files. You can see the feedback in the tree, so the text felt unneeded.
Additionally, asking if I wanted to copy a file/folder after I told it to paste said file/folder felt a bit "extra", so I got rid of it.
If there are any changes you want, I'd be happy to make them :)
And if you …
> Change filesystem actions to be immediate, minor changes to UX

- lua/nvim-tree/config.lua
- lua/nvim-tree/lib.lua
Fixes #341.
@kyazdani42 Please take a look at this when you have time. While I was implementing the window picker I had to interact with the `open_file` function, and I noticed that it was strangely obscure. It has some hard to read, 150+ character long, chained ternary expressions, and variables that change type depending on several conditions.
I refactored the function, focusing on improving the readability of the logic flow, and avoiding the long chained ternary expressions. I did this while carefully trying to ensure that the behavior is exactly the same as before, while also fixing some of the oddities, like i.e. those described in 341.
One thing I *did* change was what windows its allowed to interact with. Specifically I don't think it should interact with windows outside the …
> refactor: `open_file`

- lua/nvim-tree/view.lua
I'm using `vim-surround` which has binds like `cS`, and when I want to copy a file within the tree it waits for the timeout. Nowait fixes that.
> Set nowait on mappings to avoid timeout for conflicting mappings.

- doc/nvim-tree-lua.txt
- lua/nvim-tree/lib.lua
Close the tree if nvim_tree_quit_on_open is enabled, otherwise retain
focus on the tree.
> feat(lib): Improved tabnew behavior.

- lua/nvim-tree/lib.lua
> fix(lib): Handle nvim_win_get_option correctly when it fails.

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/config.lua
- lua/nvim-tree/lib.lua
Fixes #400.
Adds a new option `g:nvim_tree_window_picker_exclude`, that lets you exclude certain buffers from the window picker.
Example:
```vim
let g:nvim_tree_window_picker_exclude = {
\   'filetype': [
\     'packer'
\     'qf',
\   ],
\   'buftype': [
\     'terminal'
\   ]
\ }
" Dictionary of buffer option names mapped to a list of option values that
" indicates to the window picker that the buffer's window should not be
" selectable.
```
> feat: Option for excluding buffers from the window picker.

- README.md
Adds a function `NvimTreeOSOpen()` to the `README` tips section, which opens the node under the cursor in the OSs default application.
> Add function to open current node with OS default app to README tips section

- lua/nvim-tree/config.lua
- lua/nvim-tree/lib.lua
Fixes #412.
Reload git roots before refreshing nodes so that the gitignore map is
updated, and ignore rules are applied correctly on refresh_entries.
> fix: Gitignore rules not being applied on new nodes.

- lua/nvim-tree.lua
- plugin/tree.vim
Fixes #416, #418, #419.
This reverts commit be184bd94e558b302461b359d02ed1b01f7154a1.
@kyazdani42 I still don't fully understand what this commit is supposed to accomplish, but it is certainly not working correctly, and it's currently causing all sorts of strange behavior. I think we should revert this until we can figure out a better way to do it.
> Revert "feat: reset old window when leaving the tree"

- lua/nvim-tree/populate.lua
- lua/nvim-tree/renderer.lua
This adds the support for different icons when dealing with files that have multiple extensions (like `users.test.js`).
The motivation for this is based on [this issue from nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons/issues/36).
Given this sample config file for [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons):
```lua
require("nvim-web-devicons").setup {
override = {
["test.js"] = {
icon = "ﭧ",
color = "#cbcb41",
name = "JsTest"
},
["spec.js"] = {
icon = "",
color = "#cbcb41",
name = "JsSpec"
},
["test.lua"] = {
icon = "ﭧ",
color = "#51a0cf",
name = "LuaTest"
},
["spec.lua"] = {
icon = "",
color = "#51a0cf",
name = "LuaSpec"
}
},
default = true
}
```
> Improve icon fetching by file extension

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- plugin/tree.vim
this feat allows to hijack the cursor to set the cursor on the start of the filename for each line. If you wish to disable it, set `let g:nvim_tree_hijack_cursor=0`
> feat: hijack cursor

- README.md
With the original example I couldn't get it to work except for when you use `let g:nvim_tree_special_files = []`.
This would probably fix #410
> [Readme] Use correct example for special files

- lua/nvim-tree.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/renderer.lua
- lua/nvim-tree/view.lua
Initial commit includes:
- refactor `view.View.tabpages`
- refactor `view.get_winnr`
- add `view.is_help_ui`
- add basic help ui setup in `renderer.draw`
Resolves #456
TODO:
Current look for default keybindings:
> feat: Help UI for keybindings

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/view.lua
Allows nvim_tree_width to accept a string, that will determine whether or not it's a percentage of width of entire editor in columns.
Following @sindrets proposal from the previous pull request.
> add option to make width a percentage of "&columns"

- lua/nvim-tree/renderer.lua
- lua/nvim-tree/view.lua
Allows users to provide a name for a custom keybinding, instead of displaying the full callback string (which is often quite long)
- allows users to pass a `name` key when defining a custom binding
- defaults to the `cb` string when `name` is not present
- `name` key is ignored for built in callbacks
> feat(help ui): allow custom names to be provided for custom keybinds

- lua/nvim-tree.lua
- lua/nvim-tree/populate.lua
nvim-tree currently opens file with its absolute path, so ctrl-g and echo expand('%') can return a really long path that's hard to read.
This PR make nvim-tree open/preview file with its relative path. It works for both files and links.
If the current file links to a another file which is outside current working directory, nvim-tree opens the file with its absolute path.
Should fix https://github.com/kyazdani42/nvim-tree.lua/issues/482
> open file with relative path when possible

- lua/nvim-tree/populate.lua
Closes #493
When a symbolic link points to an invalid path, the value of `link_to`
equals `nil`. This value makes `utils.path_relative` throw an error,
since it expects a string as the first argument
> Fix error caused by broken symlinks

- lua/nvim-tree/lib.lua
- lua/nvim-tree/populate.lua
Attempts to fix #453
On large git repos, `git status` related commands are very slow. Do not populate git status when not set in configuration.
in nvim config:
```
vim.g.nvim_tree_gitignore = 0
vim.g.nvim_tree_git_hl = 0
vim.g.nvim_tree_show_icons = {
git = 0,
}
```
When cd'd into my huge git repo:
```
$ time git -C . status --porcelain=v1 --ignored=matching
git -C . status --porcelain=v1 --ignored=matching  6.12s user 39.51s system 737% cpu 5.513 total
```
**Before fix**
**After fix**
> fix: don't populate git status when git unused

- lua/nvim-tree.lua
- lua/nvim-tree/populate.lua
reverts 3 commits (particularly one) that introduced too many bugs.
fixes #514 #507
> fix: revert relative path

- doc/nvim-tree-lua.txt
Now that nvim 0.5 is stable (and nightly >= 0.6), replace **neovim nightly (>= 0.5.0)**  by **neovim >= 0.5.0** in doc
> fix(doc) neovim required version

- lua/nvim-tree/view.lua
Hello! I've run into a small issue with nvim-tree caused by the fact that currently, the order in which buffer options are set isn't fixed because of `pairs`. Specifically, setting `filetype` before `buftype` can cause issues for `FileType` event listeners that rely on checking `buftype`. This small PR switches to `ipairs` to make sure that the options are set in a predictable order. Let me know if this is OK!
> fix: guarantee order of buffer options

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/view.lua
This feature is equivalent to "reveal" in nerdtree or "execute_system" in defx.
Open a file with default system application by pressing `s`
Open a folder with system file manager by pressing `s`
Tested on Linux.
Should work also on MacOS, Windows, Windows Cygwin and systems using `xdg-open`, like FreeBSD.
> Feature: open file/folder with default system application

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/lib.lua
Added a new option that respect the current buffer's cwd. Nvim-tree changes its cwd to that of buffer's when this option is enabled and nvim-tree is opened.
This ensures that the cwd of nvim-tree is same as that of buffer's.
> Added new option, respect_buf_cwd

- lua/nvim-tree.lua
- lua/nvim-tree/view.lua
Following me opening https://github.com/kyazdani42/nvim-tree.lua/issues/544, I had a look inside the code (lua seems very cool), and tried the following thing to allow to not autofocus the tree when `g:nvim_tree_tab_open` is set to 1 and a new tab is opened.
I added an `option.focus_tree` (that defaults to true to keep default behaviour of the method) to `open()` in the view module that, if set to `false`, will trigger a `wincmd p` after the tree's window has been opened.
Then in `tab_change()` (I checked: `tab_change` is _only_ call on the `TabEnter` autocmd),  `open` is called with the `focus_tree` option set to false.
This way when auto-opening the tree in new tabs, the document of the new tab is automatically focused instead of the tree.
If you want to make that behaviour …
> Feature: add the possibility to not focus tree on TabEnter when g:nvim_tree_tab_open=1

- lua/nvim-tree/lib.lua
moved the command to get cwd to before opening the file tree.
fixes execution of this config:
```
let g:nvim_tree_respect_buf_cwd = 1
```
> fix: respect_buf_cwd #567

- lua/nvim-tree/view.lua
One of the recent commits has introduced a few autocommands inside the setup function for view. The exclamation mark after the commands resets all user autocommands, so I've placed them inside an augroup to prevent this from happening.
> Add augroup to view setup

- README.md
- lua/nvim-tree/config.lua
With https://github.com/rcarriga/nvim-notify/ becoming more and more popular it's likely that issue like https://github.com/rcarriga/nvim-notify/issues/18 will pop up more often. I therefore propose adding that plugin's filetype to default `nvim_tree_window_picker_exclude`.
> feat(config): add notify to nvim_tree_window_picker_exclude

- lua/nvim-tree/renderer.lua
This is mainly to avoid rendering a padding for a non-existent icon
making the nodes misaligned for no apparent reason
Fix issue #632
> Only renders the git icon if the icon is not empty

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/fs.lua
a more thorough description of the feature in #622 
Seems like this is the first instance of an option for the `fs.lua` module, so I decided to go with directly adding the variable there.
This was the only name I could think of that made sense, but I'm not sure if it makes _enough_ sense, so please do help me think of a better name if so.
Please do tell me if there's anything that I should change! Thanks :)
> feat: option to set path destination to parent folder when cursor is on a closed folder while creating files

- doc/nvim-tree-lua.txt
Currently when running `:helptags ALL` there is a `E154: Duplicating tag "nvim-tree-options"` error. This change fixes it.
> Remove duplicate 'nvim-tree-options' tag.

- lua/nvim-tree.lua
I found two issues in the ```system_open``` keypress callback (at least on linux).
The first one was easy, the functions was using an undefined flag ```_config.is_linux``` (that was always returning false) instead of the correct flag ```_config.is_unix```.
The second issue I didn't quite understand yet. From the 'xdg-open' error message I manage to realize that the table ```process.args``` was persisting its state throughout the callback calls, and each time the current file path was being appended to it, causing errors after the first call.
I don't know why this table is not redefined after each call, but I could solve the issue removing the file path from the end of the table right after spawn the process.
> fix 'system_open' keypress callback

- lua/nvim-tree/config.lua
I think those are missing as the docs say that those icons are present by default but it isn't. Below are the icons
> fix: add missing icons for `default` and `symlink`

- lua/nvim-tree/diagnostics.lua
Change color group to `DiagnosticWarn` for [nvim-0.6](https://github.com/neovim/neovim/blob/725cbe7d414f609e769081276f2a034e32a4337b/runtime/doc/diagnostic.txt#L192).
> fix(nvim-0.6): wrong color group for warning sign

- lua/nvim-tree/lib.lua
If `close_node` was called on a file, the parent folder is collapsed, but the ui was not being redrawn.
> fix: close_node behavior on file

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/view.lua
This PR contains one commit that allows us to configure the line number, just like we would do with our regular buffers. 
Default behaviour:
Just number:
Just relative number:
Number and relative number:
> feat: allow number and relativenumber settings

- lua/nvim-tree.lua
This causes out of range error on CursorMoved event is fired if hijack_cursor option is set to true.
Although I don't know why it fixes the issue, but it has been working fine for me.
Potentially fix #783, #803
> fix: idx passed to api.nvim_win_set_cursor may be -1

- lua/nvim-tree/lib.lua
Fixes #783 and #831
Redraw was not called when cwd is not a git repo.
> Fix redrawing tree when not inside git repo

- lua/nvim-tree/diagnostics.lua
Fixes #833
Continues to work on older version of neovim by using old API if new one doesn't exist.
> Fix for deprecated vim.lsp.diagnostic.get_all

- lua/nvim-tree/view.lua
Just adds a check to see if any of the other windows are not floating before closing nvim-tree.
Raised in nvim-notify in https://github.com/rcarriga/nvim-notify/issues/45 and also fixes the issue #859
> fix(view): check wins are floating

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/diagnostics.lua
This PR adds the ability to show diagnostics on a closed directory if it has child nodes with diagnostics.
The feature can be enabled/disabled via `diagnostics.show_on_dirs` option.
> Show diagnostics on directories

- doc/nvim-tree-lua.txt
Hello! I'm the author of the file manager plugin [dirbuf.nvim](https://github.com/elihunter173/dirbuf.nvim).
It seems dirbuf is incompatible with nvim-tree's `update_to_buf_dir` option in the same way that `vim-dirvish` is, so I added a warning to the documentation about this alongside the warning about vim-dirvish. I'm also adding similar warnings to dirbuf's documentation
Related: https://github.com/elihunter173/dirbuf.nvim/issues/2
> docs: Warn about dirbuf.nvim in `update_to_buf_dir` docs

- doc/nvim-tree-lua.txt
- lua/nvim-tree/git/init.lua
- lua/nvim-tree/populate.lua
See #813 for more details.
The commit 6662b60a2bb55f0c1eca4db54cba5c57c2b2daff introduced a breaking change in the plugin, as the git ignored folders/files could not be highlight anymore. This was caused by the decision to not include the parameter `--ignored=matching` in the git runner command when the user wants to *show* the ignored files, resulting in a `nil` git status for this files and making impossible to the renderer functions to set the proper highlights.
This PR aims to restore the previous behavior by  including `--ignored=matching` in all git commands. I think this is the only way to get the old behavior without changing the current config.
In order to be possible to get this behaviour *and* keep the possibility to call git without the  `--ignored=matching` (for possible …
> restore-feat: highlight-git-ignored-files

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/config.lua
- lua/nvim-tree/view.lua
This allows to define custom keybindings in configuration that receive the node as a parameter. Something like:
```lua
local tree_cb = require'nvim-tree.config'.nvim_tree_callback
local function print_node_path(node) {
print(node.absolute_path)
}
require'nvim-tree'.setup {
view = {
mappings = {
list = {
{ key = "s", cb = tree_cb("vsplit") }, -- deprecated
{ key = "t", action = "tabnew" },
{ key = "p", action = "print_path", action_cb = print_node_path },
}
}
}
}
```
I use it to run a script in the node absolute path. Let me know if this could be useful for others and I will write down the docs.
Thank you so much for this awesome plugin!!!
> custom node keymaps

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/actions/open-file.lua
I would like to open new files in the most left window by default, but
have the option to select a specific window when needed. Currently the
window picking logic is either enabled or disabled, but adding this mode
allows different keybindings for both situations.
This allows me to choose to either open it in the default windows with a
single keypress (which is often my default behavior), or to open it with
the picker asking me where I want it to be opened.
Curious what you think of this. Name of the mode or the default keybinding
can of course be changed to whatever you feel is a good name or binding,
but I would really like to be able to use this functionality. Thanks!
> Add a mode that allows edit without the picker

- lua/nvim-tree/actions/trash.lua
it seems like when the actions system was implemented the trash feature was not tested, this fixes #913  and #881
> fix(actions) trashing

- lua/nvim-tree/lib.lua
Hello, I stumbled upon issue similar to #843: when you have `hide_root_folder = true` and try to close an open node, cursor selects the node after the parent.
Ascii cinema:  [before](https://asciinema.org/a/Ky5j2nYUDh5W5COMIUSVlmB6U), [after](https://asciinema.org/a/ZTYpHqJFdkDUvfdpHUqVzHbmt)
> fix: parent_node offset when hide_root_folder is true

- lua/nvim-tree/lib.lua
[before](https://gyazo.com/f9119737f4bb2707d75798e75cc6f310), [after](https://gyazo.com/7e5753a86f637c02fe71db074b5cae79)
> fix: update diagnostic icon when a node is closed 

- lua/nvim-tree/view.lua
> fix: disable highlighting 'number' when CursorLine is enabled

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
I was finding that this plugin was causing a weird delay every time I saved a file, and traced it down to the `au BufWritePost` autocommand, which was reloading the explorer every time.  So I added support for a new option to disable this feature, for users like myself that prefer the extra performance when saving files.
I actually think the default should be to have this off, but since this would be a breaking change, I set the default as true.
> Added a new option `auto_reload_on_write`

- lua/nvim-tree/actions/change-dir.lua
- lua/nvim-tree/actions/dir-up.lua
- lua/nvim-tree/utils.lua
Without this fix, if `cwd` has a trailing slash, then user has to trigger `dir-up` action multiple times for it to work
Was also finding an issue with the `find-file` action, and the cause there was in the path_join method for a similar reason
> Fixed some trailing slash bugs

- lua/nvim-tree/lib.lua
bufnr is nil when opening quickly:
```
Vim(lua):E5108: Error executing lua ...nvim-tree.lua/lua/nvim-tree/view.lua:225: Expected Lua number
[C]: in function 'nvim_buf_is_valid'
...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:225: in function 'is_buf_valid'
```
Reproduce:
1. Set keymap, eg: `map <leader>1 :NvimTreeOpen<cr>`
1. **Fast press**: `<leader>1` when nvim starting
> fix: bufnr is nil when incomplete setup

- lua/nvim-tree/actions/reloaders.lua
- lua/nvim-tree/explorer/node-builders.lua
- lua/nvim-tree/explorer/reload.lua
fixes #966 .
@alex-courtis @victorheid can you confirm ?
> fix: reload git status of existing nodes

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/change-dir.lua
- lua/nvim-tree/actions/find-file.lua
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/actions/reloaders.lua
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/renderer/init.lua
- lua/nvim-tree/view.lua
Buffer management rewritten to be completely wiped out when closing the view. 
Buffer is properly intanciated when needed.
Started to make a proper api for the view, to avoid mutating the internals from the outside (and thus leaking abstractions to the callers).
The autocmds have been a bit cleaned up, less indirections.
Renamed `update_to_buf_dir` to `hijack_directories` wich makes more sense.
Sessions with a tree buffer will open with the tree (without the state saved).
Also added ability to open with a path like `:NvimTreeOpen /some/dir`.
Renamed `view.win_open` to `view.is_visible` (BREAKING).
Doesn't load the directory on setup when not needed, which should improve startuptime.
Fixes #601
Fixes #488 
Fixes #965 
Fixes #238 (possible to setup `open_on_setup` to `false` and …
> refacto: buffer management, setup fixes, autocmd fixes

- lua/nvim-tree/explorer/init.lua
- lua/nvim-tree/utils.lua
I notice that `path_normalize` here is to change path like `/home/young/foo/..` to `/home/young`.
But it may not handle paths like `/home/young/../xavier` correctly.
https://github.com/kyazdani42/nvim-tree.lua/blob/3f4ed9b6c2598ab8304186486a05ae7a328b8d49/lua/nvim-tree/utils.lua#L225-L229
> fix: use fs_realpath to normalize path

- lua/nvim-tree.lua
- lua/nvim-tree/utils.lua
This fixes #953.
Relative upstream issue: https://github.com/neovim/neovim/issues/16331
> fix: use canonical path in windows

- lua/nvim-tree.lua
If setup() is called before netrw is loaded, netrw needs to be hijacked on VimEnter instead.
> fix: also hijack netrw on VimEnter

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/init.lua
Resolves #998 
The method of unmapping is to set action to nil.
An alternative might be to add a `view.mappings.clear` however this seems simpler.
Also resolves a bug in which custom mappings for "multi key mappings" such a `{ key = {"<CR>", "o", "<2-LeftMouse>"}, action = "edit" },` would result in the key being shown twice in the help: once with the default mapping and once with the user.
> #998 allow users to unmap keys, remove user keys from default multi key maps

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/init.lua
Before, It will remove all user mappings which only have `key` and `cb`.  such as
```lua
mappings = {
custom_only = false,
list = {
{ key = 'h', cb = tree_cb 'close_node' },
{ key = { '<CR>', 'o', '<2-LeftMouse>', 'l' }, cb = tree_cb 'edit' },
{ key = 's', cb = tree_cb 'vsplit' },
{ key = 'i', cb = tree_cb 'split' },
},
}
```
> fix: use "" as flag to remove default mappings

- README.md
- doc/nvim-tree-lua.txt
https://github.com/kyazdani42/nvim-tree.lua/blob/15afe3a8b4a058e7b841a67da1e61b420465e40f/lua/nvim-tree/fs.lua#L60
Note that the actual default value is `nil` but this is currently equivalent to `0` from the user's perspective.
> fix(doc): nvim_tree_create_in_closed_folder default value

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/change-dir.lua
Allow keeping the cwd constant when changing directories inside the tree. `TreeExplorer.cwd` is the source of truth for the current root directory of the tree.
With `enable = false`, this matches the behavior of netrw.
Not changing the cwd can break some other plugins, e.g. [the lualine extension for NERDTree](https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/extensions/nerdtree.lua) (which [the nvim-tree extension uses](https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/extensions/nvim-tree.lua)) relies on `cwd` to show the directory in the status line. Those should be modified to rely on `TreeExplorer.cwd` if someone disables `change_dir`. I did exactly that change in https://github.com/Gelio/ubuntu-dotfiles/pull/1 by creating my own lualine …
> feat: allow not changing the cwd when changing directories

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/open-file.lua
There are many common windows - mostly plugin windows - that users will not want to open files in.
buftype `nofile` covers many vim and plugin cases such as man page, tagbar, bufexplorer etc. This saves the user from having to manually exclude all those filetypes.
filetype `diff` covers regular vim diff, as well as many plugins that use diffs such as vim-gitgutter and fugitive.
filetype `fugitive` is explicitly present as some of its buffers have an acwrite buftype. I added this as it is very popular, but happy to remove.
> add more sensible defaults for window_picker.excludes

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/explorer/node-builders.lua
- lua/nvim-tree/explorer/utils.lua
Fixes #1039 for files only. I'll wait for feedback on whether you like this feature or not before investigating why it's not working on directories. I was thinking that directories will always be sorted above files at the same level. So for each node, show `sorted(directories)` followed by `sorted(files/symlinks)`. What do you think?
> feat: add sort_by option to sort files by modification time

- lua/nvim-tree/actions/init.lua
I believe this is better matches expectations when pressing 'q' on the help ui.
> Close help on q/close instead of ignore keypress

- lua/nvim-tree/actions/run-command.lua
Handle the node representing the current directory (the topmost node in the nvim-tree window). That node does not have the `absolute_path` set. Use `TreeExplorer.cwd` instead, similar to the logic in `change-dir`.
1. `:NvimTreeOpen`
2. `gg`
3. `.`
Before:
After:
> fix(run-command): handle current directory node

- lua/nvim-tree/actions/file-popup.lua
- lua/nvim-tree/explorer/node-builders.lua
- lua/nvim-tree/explorer/utils.lua
- lua/nvim-tree/utils.lua
And refactor code so you don't have to call fs_stat everywhere.
> feat: add file size in popup

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/collapse-all.lua
Sometimes I want to "clean up" my nvim-tree but keep the directories open, which are opened in buffers at the moment.
> feat: make it possible to collapse the tree but keep the directories open which are in used in buffers

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/log.lua
Added date to logs.
Added option to truncate existing log.
> #1060 use one log file with the option to truncate

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/actions/toggles.lua
- lua/nvim-tree/explorer/filters.lua
- lua/nvim-tree/legacy.lua
> #857 add filter_custom action, filter_ignored->filter_git_ignored

- lua/nvim-tree/renderer/init.lua
This PR fixes issue with `NvimTreeFolderIcon` highlight when `vim.g.nvim_tree_highlight_opened_files` is set to 1 as mentioned in #1070 
See below screenshots for reference.
Before fix
After fix
> fix: folder icon highlight

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/open-file.lua
- lua/nvim-tree/view.lua
- update-default-opts.sh
- remove defaults from bug template
- script to update defaults in readme, help
- move the following to DEFAULT_OPTS
- view
- trash
- window picker
- add empty mapping defaults; this bugged me when I started, as I didn't know _where_ to put my mappings
> #1050 #1068 various default options tweaks

- lua/nvim-tree/actions/search-node.lua
It is possible that I am missing the point, however it seems to me that search is not working.
Changes:
- rewrote to use filesystem search; node search was problematic and complex
- matches input that exactly matches the end of a path e.g. `file1` `dir1/` `dir1/file11` but not `ir1/file11` or `le11`
- adds `:find` style command line completion for all files under cwd
Resolves:
- bug in which searching would result in two nodes would be created for the same file
Does not:
- search under the current node; searches under cwd; this could be added
Exposed:
- find-file bug around symlinks #1093
> #837 search subdirs

- lua/nvim-tree/actions/open-file.lua
This PR attempts to fix #1096. 
I set the NvimTree status line to blank when global status is set and window picker is activated. When window picker is deactivated, I restores NvimTree status line to its previous state. 
See below screenshots for reference.
Before patch
After patch
> fix: window picker bug on global statusline

- lua/nvim-tree/utils.lua
This PR tweaks `utils.rename_loaded_buffers()` behavior so now, along with renaming any exact name matches (for renaming all loaded instances of a file), it renames all children of the old path. This makes it so that renaming a directory also updates the names of any files opened within that directory or any of its subdirectories. This also makes it so `:write!` is only issued for ordinary files.
I've done basic manual testing of this change with nvim-tree.lua using both the `rename-file` and `copy-paste` actions.
For background, I recently added a feature to dirbuf.nvim where buffers are automatically renamed on moves (https://github.com/elihunter173/dirbuf.nvim/issues/18) and I stole nvim-tree.lua's code to do this! Then I enhanced it to work with directories (and not break with …
> feat: Rename child buffers when renaming directory

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/change-dir.lua
- lua/nvim-tree/actions/find-file.lua
- lua/nvim-tree/git/runner.lua
- lua/nvim-tree/log.lua
- lua/nvim-tree/renderer/init.lua
Add timing to some operations. We can add more if more slow operations are identified.
Should help us with #791
> #791 add profiling for some operations

- lua/nvim-tree/actions/search-node.lua
> #1099 search obeys active ignore filters

- lua/nvim-tree/log.lua
Use `uv.hrtime` instead of old vim method.
Adds more gates for a little optimisation when profiling not enabled.
> profile uses uv.hrtime

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- doc/nvim-tree-lua.txt
This should cover everything in #549 which we should be able to close.
I've not added the disclaimer about git status performance; it should be clear to the user ;)
> document performance issues and add to bug report template

- README.md
fixing the second " that was missing, and changing the second parameter for the toggle to true because that's how to enable the no focus toggle (as in no_focus = true)
> (readme typo) fix missing " and "toggle without focus" example

- doc/nvim-tree-lua.txt
- lua/nvim-tree/explorer/filters.lua
> #618 filters.custom can specify regex

- lua/nvim-tree/lib.lua
- lua/nvim-tree/view.lua
I saw that defaults are set on the window and the buffer however there's additional state that should be preserved across redraws, this PR adds `view.state` which keeps track of these changes, for now the only variable set is cursor.
Testing:
- Open a file from the sidebar, close the sidebar, calling `NvimTreeOpen` moves the cursor to the position of the file, this is a new behavior.
- Open a file from the sidebar, close the sidebar, cycle to another buffer opened, calling `M.find_file(with_open, bufnr)` moves the cursor to the last know state on `M.open` however the next block will find the file in the tree overriding the cursor position, this is the existing behavior.
- Open a file from the sidebar, close the sidebar, open the sidebar to see that the cursor is still on the file, create …
> Preserve cursor position across redraws

- doc/nvim-tree-lua.txt
- lua/nvim-tree/renderer/init.lua
The PR adds an `hl_group` named `NvimTreeFileIcon` which is used similarly to `NvimTreeFolderIcon`. It changes the color of file icons without the use of [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons).
Closes #1124
> feat: add hl_group for file icons

- lua/nvim-tree/actions/open-file.lua
This PR removes highlighting on `NvimTree` introduced in #1098 
Before:
After:
- Not open file if input char not included in `window_picker.chars`
> fix(statusline): better window picker highlight

- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/utils.lua
Avoid duplicates during `populate_children`.
It is not clear how this could happen, however this is safe.
> #1059 protect against duplicates

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/copy-paste.lua
- lua/nvim-tree/actions/init.lua
As requested on https://github.com/kyazdani42/nvim-tree.lua/issues/789 I've implemented an actions.opts to toggle the use of system clipboard. Default is true (use the system clipboard).
> Added actions.opts.use_sys_clipboard, [issue: 789 ] 

- lua/nvim-tree/actions/open-file.lua
This adds `bufhidden = delete` for the preview buffer, which means that the buffer will be deleted after it is no longer displayed in a window.
This value gets reset with the autocommand:
if text changes in normal or insert mode, then `bufhidden` resets and now equals to the user's `hidden` option. 
So, if you change text in preview buffer, the buffer will persist.
Also, check for `buf_loaded` is needed, so that if you press `Tab` on an already opened file, it will not become temporary with `bufhidden`
See issue #1145
> feat: delete preview buffers #1145

- lua/nvim-tree/actions/trash.lua
Trash was not working on files with spaces in the name and could even delete unwanted files.
This wraps it in double quotes, so that `trash` command receives correct filepath
> fix: trash filenames with spaces

- lua/nvim-tree/actions/copy-paste.lua
Documentation suggests that `opts.actions.use_system_clipboard` is used:
```  
actions = {
use_system_clipboard = true,
[...]
```
but the  actual property read is `use_sys_clipboard`.
Most likely just a typo - renaming it to match the documentation to avoid any confusion.
Related PR: https://github.com/kyazdani42/nvim-tree.lua/pull/1141
> fix: fix mis-naming for system clipboard config

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/diagnostics.lua
Add profiling and logging to diagnostics.
Checks canonical path of the node, to handle weird windows cases.
Closes #1091
> #1091 diagnostics logging

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/renderer/init.lua
Closes #1172 
Allows user to ignore webdev icon colours, optionally using `NvimTreeFileIcon`.
An option could have been avoided by detecting :hi NvimTreeFileIcon and using that, however there is no API to do this. Executing `:hi NvimTreeFileIcon` via pcall is error prone and slow. It also results in false positives as that group is cleared after rendering a non-webdev icon.
Most of this is a refactor. The change is commented.
> #1172 add renderer.icons.webdev_colors default true

- lua/nvim-tree/actions/change-dir.lua
- lua/nvim-tree/actions/collapse-all.lua
- lua/nvim-tree/lib.lua
Closes #1157 which raised some problems with LSP signs not being displayed or being displayed on the wrong node.
This is pretty hacky. After the renderer rewrite and moving the lsp sign to the node, renderer.draw will deal with the signs more efficiently.
These specific changes should not cause significant performance issues. Putting the update in, say, renderer.draw would work, however it would cause performance issues.
The following actions do not require changes:
```
create-file
dir-up
remove-file
rename-file
toggles
```
> #1157 update lsp diagnostics when the tree state is changed

- lua/nvim-tree/view.lua
closes #1184 
We are wiping out all tabpages during `_prevent_buffer_override` instead of the current.
> #1184 only close the current tabpage

- lua/nvim-tree.lua
This is a different approach to trying to get the behavior I was seeking out of #1201 provides a function to get the configuration as it was specified at `setup` time.
I overhauled the script I was using to use the lua autocmd api,
this script hardcodes 'width' as I didn't see any mechanism to determine the internal 'is_vertical()' from the publicly exported api.
```lua
local flex = vim.api.nvim_create_augroup("MyNVimTreeFocusResize", {clear = true})
vim.api.nvim_create_autocmd("BufLeave", {
nested = true,
callback =
function()
if vim.fn.bufname() == 'NvimTree_' .. tostring(vim.fn.tabpagenr()) then
local nvim_tree = require('nvim-tree')
local size = nvim_tree.get_config()["view"]["width"]
nvim_tree.resize(size)
end
end,
group=flex
})
vim.api.nvim_create_autocmd("BufEnter", {
nested = …
```
> add get_config

- doc/nvim-tree-lua.txt
- lua/nvim-tree/explorer/sorters.lua
I'm not sure if this is useful or not. But I guess having one more option is not a bad idea. 😄
> feat: case sensitive sorter

- doc/nvim-tree-lua.txt
- lua/nvim-tree/colors.lua
- lua/nvim-tree/view.lua
Replaced vertsplit hl groups with WinSeparator
> fix: replace vertsplit highlights (#1142)

- doc/nvim-tree-lua.txt
- lua/nvim-tree/colors.lua
- lua/nvim-tree/view.lua
Reverts kyazdani42/nvim-tree.lua#1219
See #1221
`WinSeparator` is not available as a built-in highlight group for many users.
> Revert "fix: replace vertsplit highlights (#1142)"

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/nvt-min.lua
Many bug reports are not using `nvt-min.lua`, just submitting the default.
This will "encourage" reporters to use it, with `nvt-min.lua` split out into a file.
@gegoune please can you test at https://github.com/alex-courtis/nvim-tree.lua/issues/new/choose . You will need to change the URL of nvt-min.lua `kyazdani42` -> `alex-courtis`.
> Tweak Bug Report Form

- doc/nvim-tree-lua.txt
- lua/nvim-tree/colors.lua
- lua/nvim-tree/view.lua
closes #1221
- detect `WinSeparator`, falls back to `VertSplit`
- `NvimTreeWinSeparator` defaults to `NvimTreeVertSplit`
We could put a warning about this deprecation however I do not think it is worth it.
> 1221 handle deprecated vert split

- lua/nvim-tree/view.lua
When closing the tree:
* focus the last used window in the current tab OR
* do not change focus
closes #1227 #1228
> #1228 close moves focus to previous win on current tab

- lua/nvim-tree/actions/movements.lua
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/utils.lua
Now consistent with git behaviour: show diagnostic on all folders
Feature that can use this: #1245
See #1216
> #1216 show diagnostic signs on all folders

- lua/nvim-tree/explorer/common.lua
- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/node-builders.lua
- lua/nvim-tree/explorer/reload.lua
closes #1217
naive attempt d81586e419adeee5007257827852fc030f3476a3 was ugly and duplicated logic, hence the refactor.
Priority for git status:
1. link itself: added or untracked
2. link target
Tested:
- Dirty hard/soft link:
- untracked
- added
- Clean soft link to:
- file
- folder
- another link
- Clean hard link to:
- file
- another hard link
- Clean soft folder link:
- open
- closed
- External modification and reload
> #1217 show git status for link targets, when no status on the link itself

- lua/nvim-tree/renderer/builder.lua
closes #1253 
should not interfere with #1242
> #1253 only pad git icons when they are present

- README.md
- lua/nvim-tree.lua
- lua/nvim-tree/actions/file-popup.lua
- lua/nvim-tree/actions/open-file.lua
- lua/nvim-tree/diagnostics.lua
I am still a bit new to autocommands, so please double-check that everything works
> refactor: use lua api for user commands and autocommands

- doc/nvim-tree-lua.txt
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/renderer/builder.lua
- lua/nvim-tree/renderer/components/git.lua
- lua/nvim-tree/renderer/init.lua
This is a work in progress. It works as is but there are some caveat that i'd like to discuss first.
Right, now, we will display the first icon returned by the list of icons from the node. Should we have a smarter way of doing that ?
Also, if displaying only one icons in signs, should we also always display one icon (after and before filename for instance ?)
TODO:
Fixes #553
> feat(renderer): set git icons in signcolumn

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/find-file.lua
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/actions/movements.lua
- lua/nvim-tree/colors.lua
- lua/nvim-tree/core.lua
- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/live-filter.lua
- lua/nvim-tree/renderer/builder.lua
- lua/nvim-tree/renderer/components/padding.lua
- lua/nvim-tree/renderer/init.lua
- lua/nvim-tree/utils.lua
This PR adds the ability to filter out nodes visually in the tree. It is filtering and redrawing while typing, which should provide a good user experience.
~it is very much unfinished, there are some caveats.
I'm leaving this PR open until everything is properly finished to let people discuss what would be nice to implement and potential issues that this implementation would introduce.~
TODO:
TODO in followup PR:
- filter opened buffers
- allow user to pass custom init / deinit / matching functions.
- filter with automatic depth search
> feat(live-filter): add ability to live filter out nodes in the tree

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
I found myself pressing `r` too often to update the tree.
I think this is a rather useful feature if you create/modify/delete files in the terminal. I don't really see downsides to this, but I can put it behind a config option if needed.
> feat: reload explorer on buf enter

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
This just passes the path argument to NvimTreeOpen and ignores it if NvimTreeClose is called.
> feat: Optional path argument for NvimTreeToggle and NvimTreeFindFileToggle

- lua/nvim-tree/git/utils.lua
> feat: msys2 git support

- .luarc.json
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/reload.lua
I am now addicted to lsp lua, using https://github.com/sumneko/lua-language-server
Add a configuration file and fix a couple of nits it identified.
> add .luarc.json for lua-language-server and fix a couple of nits

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/actions/remove-file.lua
This issue was already mentioned in the past, at least in https://github.com/kyazdani42/nvim-tree.lua/issues/1012
I have set up my neovim to not close windows when I close buffers, using [qpkorr/vim-bufkill](https://github.com/qpkorr/vim-bufkill)
The way nvim-tree explicitely closes the window after closing the buffer breaks that workflow for me (note that older versions of nvim-tree didn't do that, I believe 5d8453dfbd34ab00cb3e8ce39660f9a54cdd35f3 didn't do that).
So I added a new option, `remove_file_close_window`, defaulting to true -- the current behavior. When I change it to false, it fixes my issue.
> new option: close windows displaying removed files

- lua/nvim-tree.lua
closes #1306
We have had a few cases where users have done this.
We could make nvim-tree capable of "resetting itself" and applying new config, however that doesn't seem worth the effort. We would have to tear down the autocommands etc. etc.
> feat: guard against multiple setup calls

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/copy-paste.lua
- lua/nvim-tree/actions/create-file.lua
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/actions/remove-file.lua
- lua/nvim-tree/actions/rename-file.lua
- lua/nvim-tree/actions/system-open.lua
- lua/nvim-tree/actions/trash.lua
- lua/nvim-tree/core.lua
- lua/nvim-tree/explorer/init.lua
- lua/nvim-tree/explorer/node-builders.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/explorer/watch.lua
- lua/nvim-tree/git/init.lua
- lua/nvim-tree/git/runner.lua
- lua/nvim-tree/utils.lua
- lua/nvim-tree/watcher.lua
This commit introduces watchers to update the tree.
This behavior is introduced behind an "experimental_watchers" option which should prevent instabilities.
It also adds watchers on the git module that will allow git to be updated whenever the `.git` folder changes.
It will become the default at some point.
To check:
- make sure everything is reliably connected
- let 2/3 people test this before merging
- a proper code review
Bugs encountered so far:
- not fixable apparently: git updates the index a LOT (on BufEnter < which is strange, when running git status... etcetc)
Also after some debugging, i've noticed a bug in the reloader.
New nodes where not applying git status modification on explorer reload, which caused the tree to get out of sync with git, which i've observed quite a few …
> feat(explorer): add experimental watchers

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/renderer/components/padding.lua
I add a item icon for indent_markers, make it possible to make nvim-tree view like tree command output.
When we config indent_markers to this:
```lua
render.indent_markers = {
enable = true,
icons = {
corner = "└─",
item = "├─",
edge = "│ ",
none = "  ",
},
},
```
nvim-tree view:
> feat(renderer): indent_markers add a item icon

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
This makes sense since most linux distros already ship with glib2 instead of requiring the user to tweak or install 3rd party dependencies.
> feat(trash): default command 'trash' -> 'gio trash'

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/renderer/components/full-name.lua
- lua/nvim-tree/renderer/init.lua
Referencing #1297
TODO:
- ~~add an option in `require'nvim-tree'.setup`~~
- ~~show floating window when `winsaveview().leftcol` is not zero~~
> feat: display node whose name length is wider than the width of nvim-tree window in floating window.

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/view.lua
This is only relevant for large nested folders, but I find it easier when the first selection is centered.
```help
*nvim-tree.view.centralize_selection*
Reposition the view so that the current node is initially centralized, see |zz|.
Type: `boolean`, Default: `false`
```
Hopefully this is useful for others :smile:
> feat(view): ability to centralize node initially

- doc/nvim-tree-lua.txt
- lua/nvim-tree/colors.lua
- lua/nvim-tree/renderer/components/git.lua
closes #1354 
Document highlight group links.
Add missing `NvimTreeFileIgnored` group.
> fix(#1354): add missing :hi NvimTreeFileIgnored

- lua/nvim-tree.lua
Make `open_replacing_current_buffer` reach feature parity with `open`
- Accept `cwd` argument
- Fallback to `vim.loop.cwd()` instead of `return`
> feat: add cwd arg and fallback to open_replacing_current_buffer

- lua/nvim-tree/view.lua
closes #1356 
Use `#` if available when closing last buf, falling back to next as per previous behaviour.
> fix(#1356): view.close switch_buf_if_last_buf prefers alt buf

- lua/nvim-tree.lua
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/explorer/filters.lua
- lua/nvim-tree/git/init.lua
- lua/nvim-tree/watcher.lua
- scripts/generate_default_mappings.lua
I'm not a 100% sure this works as expected for every user configuration, but tested on mine and didn't notice weird behavior.
Autocmd clear properly and set up properly on 2nd setup call
git cleared whenever tree is loaded
view is closed and reopened if open on setup is true in 2nd setup call.
fixes #1338 
superseeds #1333
> chore(setup): make setup idempotent

- lua/nvim-tree/explorer/watch.lua
- lua/nvim-tree/git/init.lua
- lua/nvim-tree/git/runner.lua
First PR of many. These can be incrementally merged.
Optimising watchers has two parts:
1. git refresh
2. file system refresh
Preventing concurrency for both is a problem as they cover a different set of files.
Avoid this problem for directory watchers by only git refreshing the sub-tree and making the sets of files the same.
Experimentation has shown that this is a substantial time save: ~1/20th for my large [test repo](https://github.com/qmk/qmk_firmware)
> feat(watcher): partial git refresh

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/explorer/watch.lua
- lua/nvim-tree/git/init.lua
- lua/nvim-tree/utils.lua
- lua/nvim-tree/watcher.lua
requires #1373 
Not very useful until we move to fs_event as fs_poll is aready throttled.
I have played around a few options but was not happy:
1. Abandon refresh when there is a refresh in progress for that directory - can miss actual changes
2. Queue one refresh when there is one in progress - can result in two refreshes, which will be a big problem when we move to real time FS events
Debounce refreshes by absolute path seems the best option.
Having multiple refresh events running for different paths is OK, as we are only looking at the FS and git for that path.
> feat(watcher): debounce FS watchers

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/expand-all.lua
Hello, guys !
A small proposal from me - an 'exclude' option to the expand_all action.
I find it useful when recursively expanding child nodes. Say you have nested '.git', or you don't want to expand some kind of 'build' directories.
This also helps if you 'expand_all' while you have selected a file, which has siblings you don't want to expand.
Dunno is it a common use case, that is why I defaulted to an empty table value.
> feat(actions): expand_all 'exclude' option

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/explorer/common.lua
- lua/nvim-tree/explorer/init.lua
Adds behaviour similar to diagnostic folders.
I considered doing this in the renderer but that became complicated. Please consider if this approach is appropriate.
> feat(#1389): add git.show_on_dirs

- lua/nvim-tree/view.lua
With `actions.open_file` enabled, when an NvimTree buffer is changed to some other buffer, the window in which that buffer swap occurs is closed.
Since the `quit_on_open` function runs on `NvimTree` `BufWipeout`, there should not be a need to close the window that holds that buffer. Looking at the code, it seemed sensible to not to call `_prevent_buffer_override` if `quit_on_open` is enabled, since at best it's a no-op, and at worst it will accidentally modify the window layout.
This issue could be reproduced by:
1. Opening an existing file `:e firstfile.txt`
2. `:vs`
3. `:lua require("nvim-tree").open_replacing_current_buffer()`
4. Replacing the NvimTree buffer with some other buffer by
`:e somefile.txt`
The window containing the buffer opened in the first step would be closed. There …
> fix(view): do not close window when NvimTree buffer is replaced

- lua/nvim-tree/actions/collapse-all.lua
- lua/nvim-tree/actions/expand-all.lua
- lua/nvim-tree/actions/find-file.lua
- lua/nvim-tree/git/init.lua
- lua/nvim-tree/iterators/node-iterator.lua
- lua/nvim-tree/live-filter.lua
- lua/nvim-tree/utils.lua
Missing one iterator (see TODO comment), because i'm not sure about the interface. This is a first attempt to clean up the repetitive code for iterators. 
Not sure this is the best implementation i could go with, but it works for now.
> chore(iterators): create Iterator module and migrate iterators to use it

- lua/nvim-tree/actions/change-dir.lua
vim.cmd only accept 1 arg, path will be discarded, see `:h vim.cmd`，so we should concate cmd and args
> fix(actions): change_dir to wrong directory

- README.md
on `:help nvim-tree.setup` I get an error `E149: Sorry, no help for nvim-tree.setup`, but `:help nvim-tree-setup` is working
> :help nvim-tree.setup -> :help nvim-tree-setup

- doc/nvim-tree-lua.txt
- lua/nvim-tree/renderer/builder.lua
- lua/nvim-tree/renderer/components/padding.lua
- lua/nvim-tree/renderer/init.lua
- lua/nvim-tree/view.lua
closes #1406
Always allows folder arrows. When using indent markers the arrows do not indent the surrounding nodes.
@milessabin please test the combinations of 
* renderer.icons.show.folder
* renderer.icons.show.folder_arrow
* renderer.indent_markers.enable
> fix(#1406): allow nvim-tree.renderer.icons.show.folder_arrow

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/dispatch.lua
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/colors.lua
- lua/nvim-tree/iterators/node-iterator.lua
- lua/nvim-tree/marks.lua
- lua/nvim-tree/renderer/init.lua
Uses the signcolum to display the mark status.
Marks are saved in memory for now, we'll see if we want to implement a
filesystem save for the marks (would not be hard).
Added `m` keybinding to toggle the mark on the node
Users can call `require "nvim-tree.marks".get_marks()` which returns a
list of absolute paths.
superseeds #612
TODO:
- small bulk rename action (in followup PR)
Fixes #221 
Fixes #51 
Fixes #595 
Fixes #509
> feat(bookmarks): add bookmark feature 

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/node/open-file.lua
- lua/nvim-tree/marks/navigation.lua
- lua/nvim-tree/utils.lua
This feature will edit the file if the node is a file, and focus the folder in the tree if the node is a folder.
Added: 
- next mark
- previous mark
- select mark (vim.ui.select)
implements part of #1413
> feat(marks): add navigation (next, previous, select)

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/dispatch.lua
- lua/nvim-tree/actions/fs/rename-file.lua
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/marks/bulk-move.lua
- lua/nvim-tree/marks/init.lua
Action is bound to `bmv`, i'm not sure if this is a correct binding. Not sure what other tree do for these kind of operations.
Implements part of #1413
> feat(marks): add bulk move action

- lua/nvim-tree/core.lua
- lua/nvim-tree/explorer/common.lua
- lua/nvim-tree/explorer/init.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/explorer/watch.lua
- lua/nvim-tree/git/init.lua
- lua/nvim-tree/watcher.lua
requires #1430
Back to fs_event, as we now have thread safe and queued debouncing.
Watchers are destroyed via node destruction.
I'd like to make nodes into a proper class, however I'll do that in a later PR. `node_destroy` will do for now.
Tested a variety of git projects; tmpfs events are now properly fired :tophat:
> feat(watcher): fs_poll -> fs_event, destroy nodes/watchers

- lua/nvim-tree/git/init.lua
This PR contains one commit to prevent the execution of Git commands even when Git integration is explicitly disabled.
To replicate the issue prior to this commit:
1. Set `git.enable` to `false`.
2. Add `print(cmd)` [here](https://github.com/kyazdani42/nvim-tree.lua/blob/06e48c29c4543331eee41753e69e3bd2235bf430/lua/nvim-tree/git/utils.lua#L8).
3. Expand multiple directories in the tree.
4. Run `:NvimTreeRefresh`.
5. Observe that multiple Git commands are printed/executed (one for each expanded directory).
Explanation: Without this commit, when `get_project_root` is called (for example as a result of executing `:NvimTreeRefresh`), `get_toplevel` (which [unconditionally executes](https://github.com/kyazdani42/nvim-tree.lua/blob/06e48c29c4543331eee41753e69e3bd2235bf430/lua/nvim-tree/git/utils …
> fix(git): prevent execution of git commands when git integration is disabled

- lua/nvim-tree/git/utils.lua
requires #1433 
profile and log raw output of the git toplevel and untracked operations
> chore(git): profile git toplevel and untracked calls

- lua/nvim-tree/explorer/node-builders.lua
- lua/nvim-tree/explorer/reload.lua
The `NvimTreeRefresh` command didn't refresh `executable` field of the `node`.
1. Open `nvim-tree` by `:NvimTreeOpen`
2. Change the executable flag of any file by `chmod` command
3. Execute `:NvimTreeRefresh`
4. The style of the file node doesn't change at all while it should be
> fix(explorer): reload `executable` stat

- lua/nvim-tree/git/init.lua
This PR contains one commit to fix an incorrect conditional that was introduced in #1433.
> fix(git): fix inverted condition logic introduced in #1433

- lua/nvim-tree/view.lua
When using `adaptive_size = true` there is some extra padding (usually around 4-6 spaces). This is happening due to the unicode characters such as file or folder icon. For example `string.len("  .hooks")` (equivalent with #string ) will return 14, but this string only needs 10 spaces to be printed.
This commit fixes this issue and sets the width of the window to the *true* `max_length` + 1 space for padding.
> fix: count unicode codepoints instead of bytes

- doc/nvim-tree-lua.txt
This resolves the syntax error when copying the example lua code for mappings.
> fix(docs) Add commas in example config for docs

- lua/nvim-tree/actions/fs/copy-paste.lua
- lua/nvim-tree/actions/fs/create-file.lua
- lua/nvim-tree/actions/fs/rename-file.lua
This will fix blocking messages in simple fs operations. 
will fix #1448
> refactor(actions): remove linefeed on info messages.

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/api.lua
- lua/nvim-tree/events.lua
before #1424
This PR adds an `api.lua` module.
We should document the API, since it will be the only place we will allow users to import from, so we can be more flexible in our internal design changes.
We will also start changing the events API, to be more concise, and we'll add migration steps on a followup PR. This is non breaking, older apis will still work. We'll add a PR to be able to `.subscribe.EventName(handle)` with an index check.
This will also allow refactoring the actions to the on_attach method.
TODO:
> feat(api): add public API module

- lua/nvim-tree/explorer/watch.lua
- lua/nvim-tree/git/init.lua
- lua/nvim-tree/utils.lua
- lua/nvim-tree/watcher.lua
Split Watcher into Watcher and Event.
Event owns the fs_event for an absolute path. `Watcher:new` always creates a new Watcher which may share an existing Event.
Node watchers use a unique context: absolute path + incremennting index
Example:
```
real
real/file
link1 -> real
sub/link2 -> real
```
- One Event created for `/path/to/real`. Two node Watchers created: `/path/to/real:1`, `/path/to/real:2`.
- Modify `real/file`: one event fires, two watchers fire.
- Open sub: node watcher created `/path/to/real:3`
- Modify `real/file`: one Event fires, three watchers fire.
- Remove `link1`: node Watcher destroyed: `/path/to/real:2`
- Modify `real/file`: one Event fires, two watchers fire.
All the refresh/draw events will now correctly occur for each affected link/directory, along with the …
> chore(watchers): Watcher shares single fs_event from Event, node watchers use unique path prefixed debounce context

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/renderer/components/padding.lua
Add an option for folder arrows to be in the same column as the indent markers of their parent
inline_arrows = true
inline_arrows = false
references: #1460
> feat: add option for folder arrows to be inline with indent markers

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
We don't have a complete story for on_attach yet, so restore the documentation for old style mappings.
As a new user, I would find it difficult to set up mappings: I don't have any examples or indication of how to create on_attach mappings for non-custom functions.
> doc: reinstate mapping doc, mark on_attach as experimental

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/actions/node/file-popup.lua
Judging by https://github.com/kyazdani42/nvim-tree.lua/pull/1042#discussion_r819384771 maybe I should put the configuration inside `actions.file_popup.nvim_open_win` instead.
> Add nvim_open_win configuration for file-popup action

- lua/nvim-tree/actions/finders/find-file.lua
- lua/nvim-tree/actions/finders/search-node.lua
closes #1480 
* detect cycles on search-node `S`
* search link paths, not target paths on find-file
expand-all is OK as it stops after `max_folder_discovery`, however it does follow cycles. We should look at that if time permits.
> fix(#1480): break symlink cycle on find-file, search-node

- lua/nvim-tree/actions/fs/create-file.lua
The issue here was that the directory path generated when a new directory was created through the `fs.create-file` function was not formatted correctly as `utils.focus_file` required, so it wasn't focused after it's creation. The solution was to remove the trailing slash on this path, which was solved using the `utils.path_remove_trailing` utility when attempting to focus the newly created dir in the above mentioned functions.
Solves https://github.com/kyazdani42/nvim-tree.lua/issues/1500
> Fix focusing directories with a trailing slash in their path doesn't work

- lua/nvim-tree/git/runner.lua
- lua/nvim-tree/git/utils.lua
- lua/nvim-tree/utils.lua
* should_show_untracked evaluates non-boolean status.showUntrackedFiles
* git.Runner status logging nil values removed before concat
closes #1494
> fix(#1494): git showUntracked value and log

- lua/nvim-tree/view.lua
closes #1503 
@alexisgeoffrey please test this fix for ~1 week.
```sh
cd <your-package-directory>/nvim-tree.lua
git pull
git checkout 1503-focus-last-win-before-close
```
> fix(#1503): focus last win before close

- lua/nvim-tree/explorer/node-builders.lua
- lua/nvim-tree/explorer/reload.lua
> fix(#1520) file type changes are not detected.

- lua/nvim-tree/marks/init.lua
> fix(#1533): make `toggle_mark` ignore non-togglable nodes.

- doc/nvim-tree-lua.txt
- lua/nvim-tree/view.lua
> fix(view): allow function for view.float.open_win_config

- lua/nvim-tree/view.lua
Given the last merged PR (#1556) suggested by @Khrees, the floating window's adaptive size has been fully blocked, making impossible to allow it for those who actually use it.
```lua
if M.View.float.enable and not M.View.adaptive_size then
-- if the floating windows's adaptive size is not desired, then the
-- float size should be defined in view.float.open_win_config
return
end
```
So i propose to check both the floating window and adaptive size configuration to avoid the resizing behavior in floating windows only when the adaptive size is disabled.
> feat(adaptive_size): floating window's optional adaptive size specification

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/renderer/builder.lua
- lua/nvim-tree/renderer/components/padding.lua
This PR adds 'indent_width' option to configure visible indent for tree nesting levels (default is 2). Both enabled and disabled indent markers are supported.
A little context: 9a02dedd92fad67b04b2a3fee2de20555956b089 seemingly removed the ability to have a compact 1-symbol width indentations (and also without indent markers it was only possible to have a fixed 2-space indents, no more, no less). This PR adds ability to have a both smaller and larger (3+) indentations.
> feat: add config option for a tree indent width

- lua/nvim-tree/actions/node/file-popup.lua
- lua/nvim-tree/live-filter.lua
This PR fixes floating nvim-tree behaviour involving pop-ups:
> fix(view): Fix filter and file info popups with float enabled

- lua/nvim-tree/renderer/builder.lua
> feat: show relative path of symlink destination

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/explorer/sorters.lua
resolves #1490 #1565
adding `mixin` sort options for `rust` like package systems
```
package.rs
package/
__inside__
lib.rs
lib/
_inside_
a.rs
b.rs
module.rs
```
> feat: Mixin Sorter (#1565) Self Solved

- lua/nvim-tree/actions/node/open-file.lua
> fix(#1553): set correct side on vim open directory

- lua/nvim-tree/git/utils.lua
it is not desired to call vim.fn.system("whole command"), hence it takes all the output of the shell, there might be undesired info be parsed into the string aswell. see #1547 for more info.
better way of calling vim.fn.system({"whole","command"}) only this way the desired output of the command can be guarantied.
resolves #1547
> fixing the call to vim.fn.system

- lua/nvim-tree/actions/node/open-file.lua
``` lua
-- lua/nvim-tree/actions/node/open-file.lua
local function open_in_new_window(filename, mode, win_ids)
local target_winid = get_target_winid(mode)
if not target_winid then
return
end
:
:
-- check "not target_winid" twice
if not target_winid or not vim.tbl_contains(win_ids, target_winid) then
:
:
```
> fix: remove unnecessary conditions

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
Investigating #1270 and found some bugs and inconsistencies:
Bugs: `open_on_setup_file` overrides `open_on_setup`
Inconsistencies: `hijack_directories` overrides `open_on_setup`. Not necessarily a bug, however this behaviour has been updated to match the documentation.
Documentation has been clarified.
> fix(#1270): open_on_setup_file does not override open_on_setup, hijack_directories does not override startup behaviour

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/node/open-file.lua
- lua/nvim-tree/live-filter.lua
I like the float mode of the treeview, however I'd like it not to autoclose when the popup loses focus.
So I've added an option to that effect.
> feat: add float autoclose option

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/utils.lua
- lua/nvim-tree/view.lua
fixes #1629
[find_existing_windows](https://github.com/nvim-tree/nvim-tree.lua/blob/54afa503a978164204716a98fb67fb21cbd10017/lua/nvim-tree.lua#L136) misidentifies a buffer named `*NvimTree*` as the tree's buffer.
* `setup` -> `on_enter` -> `find_existing_windows` is the only codepath
* view is always closed in `setup`
∴ this may be removed
> fix(#1629): nvim start with file named *NvimTree* opens tree instead of buffer

- lua/nvim-tree/actions/node/open-file.lua
fixes #1626
splitright and splitbelow were not being obeyed when splitting a non-nvim-tree window.
> fix(#1626): obey splitright/below when splitting existing windows

- lua/nvim-tree.lua
I'm using the center feature, I was tracking down why I was unexpectedly getting some 'z' somewhere, then I realized that this feedkeys on focus was causing it. Calling through norm should achieve the same outcome but in a more controlled manner.
> fix: autocenter: avoid use of feedkeys

- lua/nvim-tree/view.lua
> chore(#1649): remove workaround for https://github.com/neovim/neovim/issues/17395 which was fixed in nvim 0.7.0

- lua/nvim-tree/actions/node/open-file.lua
- lua/nvim-tree/view.lua
fixes #1643
My changes prevent nvim-tree from using already closed window, usually when using floating window mode.
More details in the issue #1643
> fix: preview on floating window

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
resolves #1664 
#1618 removed this functionality; this PR restores it.
Behaviour is unreliable when netrw is enabled, usually opening netrw. See #1607
> fix(#1664): respect hijack_directories.enable on startup when not open_on_setup

- README.md
fixes #1655
Defines the state of nvim-tree via a roadmap, encouraging the use of the API rather than feature requests.
> doc(#1655): add roadmap and expand on API/events/actions

- lua/nvim-tree/actions/init.lua
> 1676 case insensitive mappings

- lua/nvim-tree/actions/node/open-file.lua
fixes #1671 
When the previous window is unavailable (quit) the first window as per the window picker order will be used for split.
> fix(#1671): split with no window picker will always find an available window

- lua/nvim-tree/live-filter.lua
Currently, if you attempt to type regex during live filter, such as "filename_[1-5]", nvim-tree will  throw errors after the opening bracket due to invalid regex.
```
Error executing vim.schedule lua callback: ...packer/start/nvim-tree.lua/lua/nvim-tree/live-filter.lua:54: couldn't parse regex: Vim:E769: Missing ] after %s[
[C]: in function 'regex'
...packer/start/nvim-tree.lua/lua/nvim-tree/live-filter.lua:54: in function 'matches'
...packer/start/nvim-tree.lua/lua/nvim-tree/live-filter.lua:79: in function 'iterate'
...packer/start/nvim-tree.lua/lua/nvim-tree/live-filter.lua:71: in function 'iterate'
...packer/start/nvim-tree.lua/lua/nvim-tree/live-filter.lua:82: in function 'apply_filter'
...packer/start/nvim-tree.lua/lua/nvim-tree/live-filter.lua:88: in function …
```
> fix: use pcall to prevent live-filter regex errors

- lua/nvim-tree/renderer/components/full-name.lua
https://github.com/nvim-tree/nvim-tree.lua/issues/1679#issuecomment-1291030546
> fix: reduce signcolumn/foldcolumn from window width

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/fs/copy-paste.lua
- lua/nvim-tree/api.lua
There does not appear to be any way to empty the clipboard other than going back to each file and removing it. This will add the command to empty it all at once (currently left unbound by default).
> feat: command to clear the clipboard

- doc/nvim-tree-lua.txt
- lua/nvim-tree/api.lua
- lua/nvim-tree/marks/init.lua
No commands are available to clear all marks at once, only toggle on and off once at a time. This adds a command to clear all marks.
> feat(api): add api.marks.clear

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/fs/copy-paste.lua
- lua/nvim-tree/actions/fs/create-file.lua
- lua/nvim-tree/actions/fs/remove-file.lua
- lua/nvim-tree/actions/fs/rename-file.lua
- lua/nvim-tree/actions/fs/trash.lua
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/actions/tree-modifiers/expand-all.lua
- lua/nvim-tree/events.lua
- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/legacy.lua
- lua/nvim-tree/log.lua
- lua/nvim-tree/marks/bulk-move.lua
- lua/nvim-tree/notify.lua
- lua/nvim-tree/renderer/components/git.lua
- lua/nvim-tree/utils.lua
- lua/nvim-tree/watcher.lua
add `notify.default_level` to setup opts
fixes #1502
> feat: configurable notification level

- lua/nvim-tree/actions/node/open-file.lua
fixes #1711
One line fix is to return -1 instead of nil when no available window.
Refactored and documented for clarity.
Tested:
* #1671 cases
* no picker, no window available
* picker,  no window available
* no picker, window available
> fix(#1711): open in a new window when no window picker and no available window

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/explorer/watch.lua
#1606
Add `filesystem_watchers.ignore_dirs`.
Tested:
* exact path
* trailing directory
* project directory
* escaped specials like `\\.`
> feat(watcher): add filesystem_watchers.ignore_dirs

- lua/nvim-tree/watcher.lua
#1606
Tear down Event / Watcher on any failure, warning the user.
Synthetic test:
`[NvimTree] File system watcher failed (EPERM) for path /tmp/1606/xxx, halting watcher.`
> feat(watcher): tear down watcher on failue, warning the user

- lua/nvim-tree/actions/finders/find-file.lua
closes #1723
`find-file`
* search root node
* always expand / populate nodes to refresh unwatched contents
> 1723 unable to open directory with new file

- lua/nvim-tree/actions/fs/create-file.lua
- lua/nvim-tree/actions/reloaders/reloaders.lua
fixes #1716 
Synchronous refresh is always performed on creation. Node is found following create/refresh.
> fix(#1716): focus file/directory when created in a sub-directory, don't dispatch FolderCreated on file creation

- lua/nvim-tree/watcher.lua
Hi. `utils` may not have a field `notify` and this PR removes it.
> utils may not have a notify field

- lua/nvim-tree/explorer/watch.lua
- lua/nvim-tree/git/init.lua
- lua/nvim-tree/watcher.lua
fixes #1720
supersede #1725 
`.git` watches only for useful files.
Use case: git operations that don't affect files, such as stage, commit etc.
Tested:
* add
* restore --staged
* commit
* revert
* init - not functional but not a regression
> fix(#1720): .git watch only FETCH_HEAD, HEAD, HEAD.lock, config, index

- lua/nvim-tree.lua
- lua/nvim-tree/actions/root/change-dir.lua
resolves #1728
fnameescape before expanding to prevent expand from substituting environment variables
> fix(#1728): escape cwd changes to prevent environment variable expansion

- lua/nvim-tree/actions/tree-modifiers/collapse-all.lua
Fixes [issue 1740](https://github.com/nvim-tree/nvim-tree.lua/issues/1740)
If we set `node.open` indiscriminately (e.g. for files) then we fail later on this line when we try to draw the tree.
First we will recurse here on a file:
https://github.com/nvim-tree/nvim-tree.lua/blob/master/lua/nvim-tree/renderer/builder.lua#L263-L267
And then `tree.node` will be `nil` here:
https://github.com/nvim-tree/nvim-tree.lua/blob/master/lua/nvim-tree/renderer/builder.lua#L285
> fix(#1740): set open state only on folders

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/diagnostics.lua
> feat: Support diagnostics severity

- doc/nvim-tree-lua.txt
- lua/nvim-tree/colors.lua
- lua/nvim-tree/renderer/builder.lua
closes #1674
The issue proposed `NvimTreeFolderIconOpen`  as the name for this hl-group, but I went with `NvimTreeOpenedFolderIcon` to stay consistent with `NvimTreeOpenedFolderName`.
This defaults to just `NvimTreeFolderIcon`, so nothing changes if you don't set `NvimTreeOpenedFolderIcon`.
> feat: Add highlight group for opened folder icon

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/renderer/components/git.lua
fixes #1781 
On certain projects there might be deeply nested folders (e.g. java projects). Showing diagnostics on all the parent folders feels very cluttered. It also makes it harder to get a idea of how many files have diagnostics at a glance.
This PR adds the `show_on_open_dirs` which when set to false will only show diagnostics on closed directory.
> feat(diagnostics): only show diagnostic and git icon on closed folder

- .github/ISSUE_TEMPLATE/feature_request.md
> docs: Update feature_request.md

- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/actions/moves/item.lua
- lua/nvim-tree/explorer/common.lua
- lua/nvim-tree/renderer/components/git.lua
closes #1786.
Not entirely sure if `explorer/common.lua` is the right place to put `has_git_status()`. To me it's kind of weird that it's constructed there tbh.
> 1786 git next prev land on dirs

- lua/nvim-tree/git/runner.lua
After renaming a file, rename icon only shows up on parent directory. No icon shows up on the file itself. This PR fixes that.
Edit: It now also deal with escape characters in quoted filenames (e.g. "a \\"quoted\\" file name") correctly
> fixed: git rename not showing up for the renamed file

- lua/nvim-tree/actions/fs/copy-paste.lua
Hey! 
Really small pr on event dispatching. 
I expect `NodeRenamed` to be triggered when I do `cut` and then `paste` some nodes.
> feat: dispatch Event.NodeRenamed on cut-paste.

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/dispatch.lua
- lua/nvim-tree/actions/finders/search-node.lua
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/actions/reloaders/reloaders.lua
- lua/nvim-tree/actions/tree-modifiers/toggles.lua
- lua/nvim-tree/api.lua
- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/filters.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/renderer/components/icons.lua
fixes #1692
```help
*nvim-tree.filters.git_clean*
Do not show files with no git status. This will show ignored files when
|nvim-tree.git.ignore| is set, as they are effectively dirty.
Toggle via the `toggle_git_clean` action, default mapping `C`.
Type: `boolean`, Default: `false`
*nvim-tree.filters.no_buffer*
Do not show files that have no listed buffer.
Toggle via the `toggle_no_buffer` action, default mapping `B`.
Type: `boolean`, Default: `false`
```
no_buffer's matching is a bit fuzzy and may miss some updates on buffer delete/wipe however it is not worth the performance cost of making it perfectly accurate.
Raised #1785 which may be completed separately.
> feat(view): add filters.git_clean, filters.no_buffer

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/fs/copy-paste.lua
- lua/nvim-tree/actions/fs/create-file.lua
- lua/nvim-tree/legacy.lua
Fixes #1800 
By default, creating or pasting a file with a closed directory selected in the tree should add the file inside of the directory. Alternately, to have them be created in the parent directory, the option `create_in_close_folder` can be set to `false`.
> Make create/paste add files to closed folders

- lua/nvim-tree/actions/fs/copy-paste.lua
- lua/nvim-tree/actions/fs/rename-file.lua
- lua/nvim-tree/events.lua
Hey!
Some language servers support [workspace/willRenameFiles](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_willRenameFiles) request. It is used in order to automatically fix imports. 
Currently neovim does not support it. So plugins must be used if one wants to use this feature. [Here](https://github.com/neovim/neovim/issues/20784?ysclid=lbgzrup04p974657325) is an open issue in neovim repo.
Since I use `nvim-tree.lua` for all file manipulations I thought it would be cool to add `WillRenameNode` event and do [workspace/willRenameFiles](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_willRenameFiles) request in the handler.
> feat(event): add will rename node event.

- lua/nvim-tree.lua
The recent implementation change to center the selected file produces a very odd error on my setup.
If I have `nvim-tree` open (for example, when opening an empty project) and then open a file using any other mean (e.g. Telescope)  a `Invalid buffer id: 1` error pops into my neovim.
Tweaking the code I've discovered the cause: the `centralize_selection` autocmd that runs when closing the tree tries to reads the `bufnr` of Telescope and then schedules the `zz` call, running after some milliseconds when the Telescope buffer is already killed.
By implicitly using the current buffer (by using `0` as a param) instead of explicitly retrieving it solves this problem. It'd probably also work if the retrieving is moved inside the `schedule` function, but haven't tried as I don't think it's better …
> fix: Implicit current buf on centralize selection

- lua/nvim-tree/actions/node/open-file.lua
closes https://github.com/nvim-tree/nvim-tree.lua/issues/1824
> fix: Don't modify jumplist when `edit_in_place`.

- lua/nvim-tree.lua
- lua/nvim-tree/actions/reloaders/reloaders.lua
- lua/nvim-tree/renderer/builder.lua
- lua/nvim-tree/renderer/init.lua
This PR refresh opened files highlight automatically whenever a buffer is read or unloaded.
> Fixed highlight-opened-files doesn't automatically refresh

- lua/nvim-tree/actions/fs/copy-paste.lua
Calling `api.fs.clear_clipboard()` produces the following error:
```
E5108: Error executing lua: ...ed/nvim-tree.lua/lua/nvim-tree/actions/fs/copy-paste.lua:135: attempt to index field 'notify' (a nil value)
...ed/nvim-tree.lua/lua/nvim-tree/actions/fs/copy-paste.lua:135: in function 'clear_clipboard'
/Users/rosswilson/Home/nvim/plugin/tree.lua:34: in function </Users/rosswilson/Home/nvim/plugin/tree.lua:33>
```
Occurs when the clipboard is cleared and attempts to notify. Updated to remove `utils` and instead use `notify` directly
> fix: clear clipboard error

- lua/nvim-tree.lua
fixes #1841
`vim.fn.filereadable` is expensive. Empty `buftype` should be good enough to detect whether it's a buffer that we can show/highlight.
Follows hotfix 4fc74ca32157ecb275e62647fbe9cff0b8e9b9c8
Follows on from #1830
> fix(#1841): do not refresh on buffer events when not a file buffer

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/fs/trash.lua
- lua/nvim-tree/actions/node/system-open.lua
- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/node-builders.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/utils.lua
> 1831 remove windows executable functionality

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/view.lua
Extends #1814
Currently, the config cursorline is set to `true` by default.
This behaviour can only be changed by a hacky way of listening to an event, as @alex-courtis mentioned that: "The user can change this default if they want via event".
This PR generalizes the configuration to be easier to config via the function `setup()`.
> feat(#1814): added cursorline config to DEFAULT_OPTS

- lua/nvim-tree/modified.lua
closes #1878.
Thanks for raising this one @alex-courtis.
The issue turned out to be path never becoming `cwd` or `"/"` no matter how many `fnamemodify(path, ":h")`. This bug would've also appeared if a file out side of the cwd is modified on windows as path would've stopped at `"C:\\"` instead of `"/"`.
I've made it so that:
- ignore buffer for modified if `buf.name` is `""`
- Don't keep looking for parents if the path is already recorded as modified, or if `fnamemodify` didn't change the path.
> Fix nvim tree frozen with no name buffer

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/api.lua
- lua/nvim-tree/utils.lua
fixes #1858
Legacy mappings only.
> feat(api): add config.mappings.current and config.mappings.default

- doc/nvim-tree-lua.txt
- lua/nvim-tree/events.lua
- lua/nvim-tree/view.lua
> feat(event): add TreeAttachedPost

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/fs/remove-file.lua
- lua/nvim-tree/actions/fs/trash.lua
- lua/nvim-tree/legacy.lua
I have a suggestion to give users the option to disable the prompt when deleting a file. For example, when working in small folders, there is no particular need to double-check the file you are deleting
> Implement turning off y/n prompt for file deletion

- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/renderer/components/git.lua
- lua/nvim-tree/watcher.lua
> feat(git): support `DA` state

- doc/nvim-tree-lua.txt
- lua/nvim-tree/watcher.lua
> fix(#1916): suppress EPERM watcher failures on windows

- lua/nvim-tree/actions/fs/create-file.lua
See https://github.com/nvim-tree/nvim-tree.lua/pull/1870#discussion_r1083594425.
For backward compatibility, when the file already exists, use early return instead of prompting to overwrite.
> fix: remove redundant file existence check in create file operation

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/api.lua
- lua/nvim-tree/lib.lua
> feat(api): api.tree.open/toggle: add current_window option

- doc/nvim-tree-lua.txt
Tag `*nvim-tree.api.tree.foucs()*` wrongly set in `api.tree.reload()` in neovim documentation.
https://github.com/nvim-tree/nvim-tree.lua/blob/f1c2d6d3723947d822930e66cd4d3351a3c0370a/doc/nvim-tree-lua.txt#L1273-L1277
> fix: documentation error

- lua/nvim-tree/view.lua
As mentioned here https://github.com/nvim-tree/nvim-tree.lua/issues/1942#issuecomment-1404397677, the `eventignore` solves the bug, that the `OptionSet` event is triggered when `nvim-tree` updates local window options.
This PR solves https://github.com/nvim-tree/nvim-tree.lua/issues/1942#issue-1554840995
> Changing window local options does not trigger OptionSet event

- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree/view.lua
with https://github.com/neovim/neovim/pull/20621 merged in it is now possible to fully customize the status-column in nvim (the column on the left containing line-numbers, fold info, signs and borders).
A fair few cool implementations have popped up like:
- https://github.com/CKolkey/config/blob/master/nvim/after/plugin/statuscolumn.lua
- https://github.com/luukvbaal/statuscol.nvim
- and my own personal one (based on CKolkey's fantastic work) https://git.hendrikpeter.net/hendrikpeter/pico-vim/-/blob/main/lua/peva/status_column.lua
The problem with nvim-tree however is that dynamic sizing doesn't take the custom size of a status column into account and the end of file names get clipped off. This little patch should fix that (and give some examples to help other status_column modders get …
> Add dynamic sizing padding options

- lua/nvim-tree.lua
> fix(#1946): only change vim's global cwd on startup when opening the tree

- lua/nvim-tree/view.lua
Looks like a debug message was left in to test for padding which causes a message to be displayed prior to the NvimTree view opening.
> Remove what appears to have been a debug message.

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
fixes #1669
Wiki with all the details: https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup
> deprecate open_on_setup

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/api.lua
open will also find file if `update_focused_file.enable = true` however that is more of a bug.
> feat(api): api.tree.open feature parity with api.tree.toggle

- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/node-builders.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/utils.lua
It appears this was causing some performance degredation.
> fix(#1831): remove instrumentation

- lua/nvim-tree/actions/finders/find-file.lua
- lua/nvim-tree/actions/root/change-dir.lua
- lua/nvim-tree/core.lua
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/git/runner.lua
- lua/nvim-tree/git/utils.lua
- lua/nvim-tree/log.lua
- lua/nvim-tree/renderer/init.lua
- lua/nvim-tree/view.lua
should be safe to merge with minimal testing as it is logging only
> fix(#1961): harden profiling functions

- lua/nvim-tree/explorer/reload.lua
> 1961 cycle detection on refresh

- doc/nvim-tree-lua.txt
> doc(#1997): clarify renderer.highlight_ and correct highlight group names

- lua/nvim-tree/utils.lua
fixes #2004
The captures creates a limit where input path cannot have more than 32 special charactors ( `.`  , `_` or `-`)
> fix(#2004): remove unintentional captures in path_to_matching_str

- lua/nvim-tree/actions/finders/find-file.lua
- lua/nvim-tree/explorer/reload.lua
fixes #1961 
Second attempt.
Direct fixes:
* avoid cycles for real and linked paths
* match paths with regex magic characters
Opportunistic fixes:
* find file does not refresh if the file is present in the tree
> fix(#1961): cycle detection on find file refresh, fix regex pattern matching on paths, do not refresh if the node is present

- lua/nvim-tree/renderer/components/git.lua
> feat(git): add `TM` git status

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/finders/find-file.lua
- lua/nvim-tree/actions/init.lua
- lua/nvim-tree/actions/tree/find-file.lua
- lua/nvim-tree/actions/tree/open.lua
- lua/nvim-tree/actions/tree/toggle.lua
- lua/nvim-tree/api.lua
- lua/nvim-tree/lib.lua
fixes #2011 
Requires dogfooding
* api.tree.find_file feature parity
* commands call API
* large refactor of open, toggle, find_file
```
legacy path        - x - - - - - - - - -
buf path           - - x - x - - - - - -
buf number         - - - x - - - - - - -
open               - - - - x x - - x x -
current_window     - - - - - x - - - x -
update_root        - - - - - - x - - - x
focus              - - - - - - - x x x -
ignore_list        - - - - - - - - - - x
```
```
path               x - - - - - - - - x x x x
current_window     - x - - - - x x x - x x x
find_file          - - x - x x x x x x x x x
update_root        - - - x x x - x x - - x x
ignore_list        - - - - - x - - x - - - x
```
```
path               - x - - - - - - - - - -
current_window     - - x - - - - x x x x - …
```
> #2011 api.tree.find file feature parity

- README.md
> doc: README installation points to wiki

- doc/nvim-tree-lua.txt
- lua/nvim-tree/api.lua
- lua/nvim-tree/keymap.lua
> feat(api): add api.config.mappings.get_keymap and get_keymap_default

- doc/nvim-tree-lua.txt
https://github.com/nvim-tree/nvim-tree.lua/commit/4f036342f14378b53ac5d7c6ae8d8f6d1bf9a0f8 added `api.config.mappings.get_keymap` and `get_keymap_default` and introduced duplicated tags in the documentation.
> fix(doc): duplicate help tag in README

- lua/nvim-tree/actions/root/change-dir.lua
Fixing #2057 
This happens because nvim-tree is trying to change the current directory to a non existing direction
> Fixing #2057

- lua/nvim-tree/diagnostics.lua
The `diagnostics.severity` option do not work properly with coc
So let it work :)
[Here](https://github.com/neoclide/coc.nvim/blob/d35b5387ba9bfff58863fd0f7919fbb3572d7b03/src/diagnostic/manager.ts#L36) is the response interface of `vim.fn.CocAction "diagnosticList"`
For the old version coc, it do not have `level` field, So I still use `severity` field
> fix(diagnostics): `severity` option do not work with coc

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/api.lua
- lua/nvim-tree/commands.lua
fixes #2076 
I would be most grateful for your review @mrjones2014
I've used the `"nvim-tree: "` prefix as per the mappings and kept it brief. Most grateful for suggestions...
> feat(commands): add descriptions

- lua/nvim-tree/actions/root/change-dir.lua
> fix(#2088): actions change dir enable false does not update tree root

- .editorconfig
- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/moves/item.lua
- lua/nvim-tree/api.lua
> feat(#2092): add api.node.navigate.open.next, prev

- lua/nvim-tree/api.lua
Regression introduced by 74959750.
Closes #2097 
@alex-courtis I have kept parity with `open_or_expand_or_dir_up` in regards to behaviour on `..`, which might not be desired. I believe we might not want to do anything in that case as it was previously?
If we do want to keep parity perhaps those two functions can be merged into one with `preview` argument.
> fix: `api.node.open.preview` should toggle directories

- doc/nvim-tree-lua.txt
> docs: help for api.node

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/node/open-file.lua
call nvim_list_wins again after the picker is run
also show a warning if it doesn't exist. I don't see why this would happen unless its a bug in the picker, perhaps something else snuck in and deleted the window
Fixes #2126
> fix: custom window pickers that create windows should work

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/node/open-file.lua
- lua/nvim-tree/api.lua
https://user-images.githubusercontent.com/8136158/233742234-c4f4bb4b-1927-4ab4-b0cc-779c64a0e1b1.mov
* Demo of the new action allowing to always jumpt to an already-opened window based in built-in command. Every time `<CR>` is hit, the same buffer window of the file is focused.
* Usage docs added
Demo link: `https://user-images.githubusercontent.com/8136158/233742234-c4f4bb4b-1927-4ab4-b0cc-779c64a0e1b1.mov`
**PREVIOUS PRs got CLOSED BECAUSE OF FORCE-PUSH, GITHUB IS REALLY NUTS**
```lua
require("nvim-tree").setup({
on_attach = function(bufnr)
local function opts(desc)
return { desc = 'nvim-tree: ' .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
end
local ok, api = pcall(require, "nvim-tree.api")
assert(ok, "api module is not found")
vim.keymap.set("n", "<CR>", …
```
> feat(api): Add new node selection action based on tab :drop command

- doc/nvim-tree-lua.txt
- lua/nvim-tree/keymap-legacy.lua
> fix(#2157): use stdpath cache for my_on_attach.lua

- lua/nvim-tree/actions/fs/copy-paste.lua
- lua/nvim-tree/actions/fs/rename-file.lua
> feat: Focus file after rename and paste

- README.md
- doc/nvim-tree-lua.txt
- scripts/update-help.sh
There is a little confusion around how to change the default mappings (briefly glimpsed on matrix chat). Added more examples.
Clarified quick start.
Build a user readable, linked table for mappings as an alternative to the default `on_attach`. Did not include it as I couldn't find a sensible place. Thoughts @gegoune ?
```help
`<C-]>`           CD                      |nvim-tree-api.tree.change_root_to_node()|
`<C-e>`           Open: In Place          |nvim-tree-api.node.open.replace_tree_buffer()|
`<C-k>`           Info                    |nvim-tree-api.node.show_info_popup()|
`<C-r>`           Rename: Omit Filename   |nvim-tree-api.fs.rename_sub()|
`<C-t>`           Open: New Tab           |nvim-tree-api.node.open.tab()|
`<C-v>`           Open: Vertical Split …
```
> docs: clarify on_attach example, quick start

- lua/nvim-tree/actions/node/open-file.lua
> fix(#2175): check number of actions.open_file.window_picker.chars before picking window

- doc/nvim-tree-lua.txt
- lua/nvim-tree/colors.lua
- lua/nvim-tree/help.lua
- lua/nvim-tree/view.lua
Currently, `NvimTreeNormal` is used for floating window's background. However, when `winblend` is set and `Normal` highlight is set to transparent, the background will turn `black`. Using `NormalFloat` allows users to customize the background and not interfere with normal window.
<details>
<summary>minimal init.lua</summary>
```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
require("packer").startup {
{
"wbthomason/packer.nvim",
--"jamestansx/nvim-tree.lua",
"nvim-tree/nvim-tree.lua",
"nvim-tree/nvim-web-devicons",
{ "catppuccin/nvim", as = "catppuccin" }
-- …
```
> feat: add `NormalFloat` hl for floating windows

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/tree/find-file.lua
- lua/nvim-tree/actions/tree/open.lua
- lua/nvim-tree/actions/tree/toggle.lua
- lua/nvim-tree/api.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/view.lua
> feat: add winid parameter for api.tree.open, toggle, find_file

- README.md
- doc/nvim-tree-lua.txt
> docs: add nvim-tree-netrw

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/git/runner.lua
> fix(#2104): remove experimental.git.async, always used

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/git/init.lua
- lua/nvim-tree/git/utils.lua
fixes #1837 
@NiklasKappel I'd be most grateful if you tested this feature:
```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 1837-git-disable-dirs
```
> feat(#1837): add git.disable_for_dirs

- lua/nvim-tree/actions/tree-modifiers/toggles.lua
- lua/nvim-tree/utils.lua
This is the refactor we discussed in #2202, it will be useful for future fixes.
I also noticed that I called `utils.focus_file` when it was unnecessary, so I replaced it with a simple `view.set_cursor`.
> refactor: move `reload` function into `utils` module

- lua/nvim-tree/diagnostics.lua
This PR adds support for checking `vim.diagnostic.is_disabled()` on nvim 0.9+. This function was added to support globally enabling or disabling diagnostics. This is especially useful for setups where diagnostics are enabled conditionally or on a project basis. There is no change in behavior for versions prior to 0.9.
Thanks for a great plugin!
> feat: support vim.diagnostic.is_disabled()

- lua/nvim-tree.lua
- lua/nvim-tree/utils.lua
- lua/nvim-tree/view.lua
fixes #1545
@wlh320 @Tcholly I'd be most grateful if you tested this fix:
```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 1545-resize-events
```
> fix(#1545): dispatch Event.Resize on all window resizes, requires nvim 0.9+

- doc/nvim-tree-lua.txt
There was a duplicate "features" in the netrw section of the docs.
> docs: fix typo in netrw section

- lua/nvim-tree/git/utils.lua
Resolves #2243
The fix happens inside a `if vim.fn.has "win32"` block and thus, does not affect WSL.
If necessary, I could install cygwin to test it on that too. Also, I wasn't sure, what test case (in CONTRIBUTING.md) meant, as I didnt find a test setup for the repo. The issue describes the exact problematic case and why this fix works for it. If more description is needed, please tell me :)
> fix(#2243): fs_watcher not started for .git folders (Win)

- lua/nvim-tree/actions/tree-modifiers/collapse-all.lua
Here's a simple fix analogous to the ones made to toggles and live filter.
> fix: focus visible parent on collapse all

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/fs/create-file.lua
- lua/nvim-tree/actions/fs/remove-file.lua
- lua/nvim-tree/actions/fs/trash.lua
- lua/nvim-tree/events.lua
Add new will-action events to complement the existing one for rename node. These are mostly going to be useful for implementing lsp file operation actions.
> feat(event): add WillCreateFile, WillRemoveFile

- lua/nvim-tree/actions/fs/copy-paste.lua
fixes #2277
@khaitranhq I would be most grateful if you tested this change:
```sh
cd /path/to/nvim-tree.lua
git pull
git checkout 2277
```
On cut/copy paste in the same directory you will be immediately promted for the name.
> feat(#2277): skip overwrite prompt when copy/cut paste into same directory

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/fs/copy-paste.lua
- lua/nvim-tree/actions/fs/create-file.lua
- lua/nvim-tree/actions/fs/remove-file.lua
- lua/nvim-tree/actions/fs/rename-file.lua
- lua/nvim-tree/notify.lua
fixes #2270
Sorry for duplicate PRs! I totally messed up with #2280. Hopefully no harm was done.
> feat(#2270): add notify.absolute_path - show file or absolute path (default) names with notifications

- lua/nvim-tree/utils.lua
Fixes #1989
An new unloaded, unlisted buffer of the source name may be created however that is acceptable; trying to clean that up is prone to error.
> fix(#1989): cut/paste overwrite deletes destination buffer

- doc/nvim-tree-lua.txt
- lua/nvim-tree/explorer/sorters.lua
Fixes nvim-tree/nvim-tree.lua#2288 by proposing a new kind of sorting: by vim's filetype.
> feat: add sort_by "filetype"

- lua/nvim-tree/explorer/sorters.lua
As suggested by @alex-courtis on #2302
> fix: sort_by "extension" falls back to name

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/explorer/sorters.lua
- lua/nvim-tree/legacy.lua
fixes #2313
`rm -rf * ; mkdir -p a/10 a/20 z/10 z/20 ; touch a/5 a/15 a/25 z/15 b`
sort_by = "name"
sort_folders_first = true
```
~/2313/..                   │
  a                       │~
  10                    │~
  20                    │~
 15                    │~
 25                    │~
 5                     │~
  z                       │~
  10                    │~
  20                    │~
 15                    │~
 b                       │~
```
sort_by = "name"
sort_folders_first = false
```
~/2313/..                   │
  a                       │~
  10                    │~
 15                    │~
  20                    │~
 25                    │~
 5                     │~
 b                       │~
  z                       │~
  10 …
```
> feat(#2313): sort_by -> sort.sorter, add sort.folders_first default true

- lua/nvim-tree/explorer/watch.lua
- lua/nvim-tree/git/init.lua
While rarely used, it's possible to set the $GIT_DIR environment variable to instruct git to use a directory other than `.git`.
This checks if that environment variable is set; if it is, the plugin will watch that directory. If it's not set, it'll fall back to the default `.git` directory.
I use a non-standard `.git` folder in my home directory for my dotfiles (`~/.git_dotfiles`). If I have `$GIT_DIR` set in my env to work on my dotfiles and open up nvim-tree, it'll detect that we're "in a git repo".
Prior to this change, it would produce an error that it can't watch the `.git` directory (since it doesn't exist). With this change, it produces no error and correctly watches the `$GIT_DIR` directory.
I tested this in my environment by opening up nvim and nvim-tree in various scenarios, …
> feat: support custom $GIT_DIR

- lua/nvim-tree.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/git/init.lua
fixes #1931
Directory is compared to known ignored from all project and status is not executed:
* first open
* refresh
> fix(#1931): do not execute git status in git ignored directories

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/fs/trash.lua
fixes #2331
Support trash-cli on Windows, relate to discussion https://github.com/nvim-tree/nvim-tree.lua/discussions/2333 and #2331.
1. remove `Unix only` from trash action.
2. set `detach=false` and `jobwait { job }` on Windows to make trash operation sync on Windows. This is because: in my testing/practicing, when set `detach=true` in jobstart, nvim (running in Windows Terminal app) quickly switch to desktop, then switch back to nvim, that makes the screen blink. I guess the **process detech** behaviour is different under Windows, to avoid this blink I set sync wait under Windows.
3. manual tested on Windows 10 x86_64, nvim v0.9.1, latest nvim-tree master.
> feat(trash): add synchronized trash support for windows

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
Hello!
In issue #1628 and PR #1637 the following expected behavior was introduced. When opening a file using `:edit` (or Telescope) while being focused on nvim-tree window, the new file opens in another window (and, depending on `quit_on_open` option, the nvim-tree window either stays or closes). This is useful when using nvim-tree in "expected" way, i.e. as a narrow column window on the side, which can be toggled on and off.
However, I'd like to use nvim-tree as a replacement of netrw: I would mostly want to open files from the tree in-place, overriding the tree window. While there already exists an API function `api.node.open.replace_tree_buffer` which performs an in-place open, issuing `:e` or using Telescope does not make the desired in-place open.
This PR adds an option …
> feat: add actions.open_file.eject

- lua/nvim-tree.lua
> fix(#2343): tree is now correctly abandoned upon an in-place open with eject=false

- lua/nvim-tree/lib.lua
> fix: prompt uses first character of response - allow "yy"

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/fs/trash.lua
> fix: trash.cmd defaults to 'trash' on macos

- lua/nvim-tree/actions/finders/find-file.lua
- lua/nvim-tree/explorer/reload.lua
fixes #2305 
fixes #2347
I think I've finally got it right this time. Recursion should be no problem as the tree is not mutated during traversal.
> feat(#2305): find file refreshes up the tree when node is not present

- doc/nvim-tree-lua.txt
There is a duplicate `node.` in the the API NODE section for `navigate.git.next`.
> docs: fix typo in API Node section

- lua/nvim-tree/actions/node/open-file.lua
- lua/nvim-tree/utils.lua
fixes #2352
- add check if environment is windows
- if windows, escape special characters
This works on windows, will need additional linux/mac testing.
> fix(#2352): windows: escape special filename characters on edit

- lua/nvim-tree/actions/fs/copy-paste.lua
- lua/nvim-tree/actions/fs/remove-file.lua
- lua/nvim-tree/actions/fs/trash.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/marks/bulk-delete.lua
fixes #2370.
Packer uses a bool flag comparing to check whether the given input is "y".
I've made it so that the default behaviour of the prompt is set to N for no (don't delete).
The default is set to R(ename) for name conflicts when copy-pasting.
Accidentally clicking enter/return after pressing d/bd should be made less common with this default behaviour.
the default behaviour is shown as a capital letter.
> fix(#2370): Better "y/N" prompts

- lua/nvim-tree/lib.lua
Currently when opening folder groups, the folder icon and arrow indicators don't change correctly.
Current behaviour:
With this fix:
> fix: expand and collapse whole folder groups

- lua/nvim-tree/actions/reloaders/reloaders.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/git/init.lua
- lua/nvim-tree/git/runner.lua
- lua/nvim-tree/git/utils.lua
fixes #2382 
This is clunky: using yet another map for project roots is fragile and not easily maintainable.
Possible refactor: make `get_project_root` private, migrating to `get_project` or similar. Trim down init to do nothing but create the entire project and watchers.
> fix(#2382): git watcher handles worktrees and submodules, via --absolute-git-dir when it is available

- lua/nvim-tree.lua
This can be useful to warn the user when a string value is not "accepted" in those cases where strings act like a sort of enum. I don't know if this can be considered a feature or something, let me know...
> feat: validate some option string values

- lua/nvim-tree/marks/init.lua
When `group_empty` is enabled, marks were misaligned if one or more parent nodes were empty. See #2392 
Followed the code logic as proposed [here](https://github.com/nvim-tree/nvim-tree.lua/commit/d8b154c5f0981886fc2b0f1e52d6172e7fdd13e4)
I'm not super confident I've taken all that needs to be into account. It seems to work (see screenshots), but it got fixed quite fast, which doesn't make me confident. Please review with that in mind!..
`group_empty` enabled:
`group_empty` disabled (showing that marks are still aligned):
I used the below tree structure (start is just a start script I made):
Below was the minimal config I was using:
```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local …
```
> fix(#2392): bookmarks vertical alignment when group_empty

- doc/nvim-tree-lua.txt
- lua/nvim-tree/colors.lua
- lua/nvim-tree/renderer/builder.lua
> feat(#2398): add NvimTreeOpenedFileIcon

- doc/nvim-tree-lua.txt
- lua/nvim-tree/renderer/builder.lua
- lua/nvim-tree/renderer/components/padding.lua
> feat(#2316): add NvimTreeFolderArrowClosed NvimTreeFolderArrowOpen

- lua/nvim-tree/legacy.lua
While testing #2414 I noticed that setting `view` to anything but a table would crash due to this problem in `legacy` module, so I fixed it.
> fix: add legacy options safety

- lua/nvim-tree.lua
Now that notifications are scheduled, having multiple line messages should not be an issue anymore. This way warnings are far easier to read.
> feat: split warning messages into multiple lines

- doc/nvim-tree-lua.txt
> docs(#2440): view.width.padding may only be a string

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
Update accepted types for view.width option so padding can be set. See #2440.
Overrides documentation change of #2441
> fix(#2440): `view.width.padding` may be a number or function returning a number

- lua/nvim-tree/actions/finders/find-file.lua
> fix(#2433): selection incorrect after find-file when renderer.group_empty

- lua/nvim-tree.lua
- lua/nvim-tree/notify.lua
Having `[NvimTree]` as a notification header while using a notification system that actually supports title is redundant, so with this simple change it will be added only if needed.
> feat: use virtual title in notifications if title is not supported

- lua/nvim-tree/renderer/init.lua
> fix(#2450): highlight for `webp` and `jxl` files

- .stylua.toml
- lua/nvim-tree.lua
- lua/nvim-tree/actions/fs/rename-file.lua
- lua/nvim-tree/actions/node/open-file.lua
- lua/nvim-tree/actions/node/system-open.lua
- lua/nvim-tree/actions/tree-modifiers/expand-all.lua
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/filters.lua
- lua/nvim-tree/git/runner.lua
- lua/nvim-tree/help.lua
- lua/nvim-tree/legacy.lua
- lua/nvim-tree/modified.lua
- lua/nvim-tree/notify.lua
- lua/nvim-tree/renderer/builder.lua
- lua/nvim-tree/renderer/components/git.lua
- lua/nvim-tree/renderer/components/padding.lua
- lua/nvim-tree/utils.lua
- lua/nvim-tree/watcher.lua
No `"if$"` remaining, adds readability.
#2449 increases to 160 however those long lines are genuinely too long. Manually resolved those, see with comments.
> chore: stylua column width 120 -> 140

- lua/nvim-tree/notify.lua
This was a little annoying:
```
[NvimTree]
notify.lua added to clipboard.
Press ENTER or type command to continue
```
> feat: notify [NvimTree] prefix is multiline only if the message is multiline

- lua/nvim-tree/actions/fs/copy-paste.lua
- lua/nvim-tree/actions/fs/create-file.lua
- lua/nvim-tree/actions/fs/rename-file.lua
- lua/nvim-tree/actions/node/system-open.lua
- lua/nvim-tree/actions/tree/open.lua
- lua/nvim-tree/actions/tree/toggle.lua
- lua/nvim-tree/api.lua
- lua/nvim-tree/commands.lua
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/help.lua
- lua/nvim-tree/keymap.lua
- lua/nvim-tree/marks/bulk-move.lua
- lua/nvim-tree/renderer/builder.lua
Discussed in #2448. Not sure if this is more of a refactor or a chore. Either way now almost every table with more than 3 members is formatted line by line, greatly improving readability.
> refactor: format tables line by line for better readability

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/git/utils.lua
> fix(#2459): disable cygwin git support by default, see :help nvim-tree.git.cygwin_support to enable

- lua/nvim-tree/utils.lua
I'm very happy that this project uses 1024 as a divisor instead of 1000. But to explicitly inform user about it the prefixes should consist of 3 letters:
- multiple (K, M, G, T)
- 'i' (bInary)
- 'B' (Byte)
Exception is any number of bytes that are less than 1024, then the prefix is just the 'B' letter.
As an addition I've completed the list with the missing prefixes: P, E, Z, Y.
Quick reference: https://en.wikipedia.org/wiki/Binary_prefix.
P.S. Ri and Qi are not yet confirmed (only SI counterparts exist starting from 2022: R, Q).
> feat: use IEC binary size prefixes

- lua/nvim-tree/utils.lua
This is a new patch after #2483.
What's new:
- Now there is a whitespace between value and unit (this is the correct way, same as in git, crates.io; see https://github.com/typst/typst/discussions/2100#discussioncomment-6961087).
- Now values >= 1024 YiB are shown in YiB instead of B.
- To reuse same code a new local function was added: round().
I've also added comments to clarify some things. The `round()` function is local, but the plugin works correctly (I thought it wouldn't). I don't know how exactly `M` from `utils.lua` is used, so I didn't do `M.round()`.
> fix: Fixed "BiB" bug and improved binary prefixes

- lua/nvim-tree/actions/fs/copy-paste.lua
Closes #2312.
I was browsing "PR please" issues and I noticed this one. If I understood it correctly this small addition should be sufficient.
> feat(#2312): fire `TextYankPost` event on path copy

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/help.lua
Just an option that is nice to have
> feat: add option to sort entries in help window

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/fs/copy-paste.lua
- lua/nvim-tree/git/utils.lua
- lua/nvim-tree/help.lua
- lua/nvim-tree/utils.lua
Fixes #2467 (potentially also for #2466), regarding failed git integration on Windows.
Background: In file git/utils.lua, the two paths variables toplevel and git_dir are returned by vim.fn.system(...), which will add a trailing newline character, causing them to be invalid paths.
Fix: Added two lines of gsub function to remove any newline characters in these paths.
After preliminary tests on Ubuntu, I suggest caution for the general behavior of vim.fn.system() on all systems, where its return value seems to always contain a trailing newline, therefore its direct return value can't be used as paths.
> fix(#2467): remove newline in git paths

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/fs/remove-file.lua
- lua/nvim-tree/actions/fs/trash.lua
> feat(#2498): add option for "Y/n" prompts

- .github/ISSUE_TEMPLATE/nvt-min.lua
> docs: add (disabled) diagnostics config to bug report template

- lua/nvim-tree/actions/fs/remove-file.lua
https://github.com/nvim-tree/nvim-tree.lua/issues/2480
> fix: error when deleting opened file from floating window

- lua/nvim-tree/actions/fs/rename-file.lua
> fix(#2507): icon in message after rename-file

- lua/nvim-tree/actions/moves/item.lua
It was really annoying to me not to have this capability
> feat: allow cycling on git/diagnostic/opened files navigation

- lua/nvim-tree/api.lua
> fix: file creation in empty folder without root_folder_label

- lua/nvim-tree/live-filter.lua
Problem: When leaving live filter overlay we delete window, but not buffer, you can debug this and found that these buffers living all time untill you close neovim.
Solution: Add buffer deletion.
Also small improvement, `vim.api.nvim_win_close` as second argument takes `force` as `boolean` not `table`(but maybe this also working) https://neovim.io/doc/user/api.html#nvim_win_close()
> fix: live filter delete buffer when removing overlay

- lua/nvim-tree.lua
Not sure if this entirely fixes #2488, but at least the tree gets reloaded when cwd has been changed by another instance of nvim-tree.
> fix: reload tree on `BufEnter` if cwd is different

- lua/nvim-tree/live-filter.lua
> fix: live filter overlay width calculation

- lua/nvim-tree/explorer/node.lua
Requisite config:
```lua
local nvim_tree_setup = function()
require('nvim-tree').setup({
on_attach = on_attach,
diagnostics = {
enable = true,
},
update_focused_file = {
enable = true,
update_root = false,
},
respect_buf_cwd = false,
sync_root_with_cwd = false,
view = {
width = 40,
side = 'right',
--mappings = {
--  custom_only = false,
--  list = {
--    { key = { '<CR>', '<Tab>' }, action = 'edit' },
--  },
--},
},
})
end
```
Occasionally, with the above config, `nvim-tree` will spit out the following error message:
`node.lua attempt to index local 'status' a nil value`
creating a nice big traceback of the complaint and stealing focus briefly. You can immediately press `q` and leave it and go back to what you were doing, but it happens a few times in a couple seconds, then chills out. …
> fix: add nil check to git status

- lua/nvim-tree/renderer/components/git.lua
sync icons with highlights:
["A "] = { icons.staged },
and 
["A "] = "NvimTreeFileStaged",
> fix: new staged files

- lua/nvim-tree/actions/reloaders/reloaders.lua
Closes #2468
I might have found a fix for #2468, and if so it's a really simple one. From my tests it seems to apply correctly all filters to all subdirs, not sure about the resource leaks but they should go together as well.
> fix(#2468): always apply filters to subdirectories

- .github/workflows/ci.yml
Brings in line with https://github.com/nvim-tree/nvim-web-devicons/pull/341
* versions pinned
* avoids ubuntu packages
> ci: ubuntu packages -> luarocks action, pin versions

- doc/nvim-tree-lua.txt
- lua/nvim-tree/api.lua
- lua/nvim-tree/view.lua
> feat(#2544): add API for querying win ID, api.tree.winid()

- lua/nvim-tree/core.lua
In a recent update, I found the restore of rmagatti/auto-session doesn't work, and from my debugging, it looks like the function `get_cwd` needs a nil check.
When `get_cwd` is used in the `autocmd` (`BufEnter`), the `core` is not initialized and thus `TreeExplorer` is nil and thus `TreeExplorer.absolute_path` throws exception, this PR adds a nil check to the `TreeExplorer`
https://github.com/nvim-tree/nvim-tree.lua/blob/de752768cf8eac363b4fb02501286234af37592c/lua/nvim-tree.lua#L287
I'm using LazyVIM
```
return {
"nvim-tree/nvim-tree.lua",
lazy = false,
dependencies = {
"nvim-tree/nvim-web-devicons",
},
config = function()
require("nvim-tree").setup {}
-- restore nvim-tree with auto-session
local api = require "nvim-tree.api"
local view = require "nvim-tree.view" …
```
> fix: add nil check to `get_cwd`

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/api.lua
- lua/nvim-tree/commands.lua
> refactor: api and command focus call tree.open(), soft deprecate tree.focus()

- lua/nvim-tree.lua
- lua/nvim-tree/core.lua
- lua/nvim-tree/live-filter.lua
I noticed that there is this `TreeExplorer` global variable that's used just twice, so I simply made it local to `core` and added a simple function to reset it when needed.
> chore: remove `TreeExplorer` global variable

- .github/workflows/ci.yml
- scripts/doc-comments.sh
Discussed in https://github.com/nvim-tree/nvim-tree.lua/pull/2555#issuecomment-1826209931
> ci: add style check for doc comments

- lua/nvim-tree.lua
> refactor(#1645): remove unused open_replacing_current_buffer

- lua/nvim-tree.lua
- lua/nvim-tree/utils.lua
> fix(#2568): hijack_cursor positions at top grouped node

- lua/nvim-tree/actions/moves/item.lua
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/node.lua
- lua/nvim-tree/renderer/builder.lua
- lua/nvim-tree/renderer/components/diagnostics.lua
The diagnostic changed event has been untied from the current tree state to ensure the data availability at any time. Now, the diagnostics will be picked up "on the fly" whenever the tree is about to be (re-)drawn, which makes absolute sense, especially, when incrementally exploring the file system structure or when (re-)opening the tree and the diagnostic changed event has already occurred.
All in all, this effectively solves any inconsistencies (see https://github.com/nvim-tree/nvim-tree.lua/discussions/2517), and ensures that the tree shows the freshest diagnostics, regardless of the tree's state and when diagnostics change.
> fix(#2519): Diagnostics Not Updated When Tree Not Visible

- lua/nvim-tree.lua
> fix: hijack_cursor with update_focused_file

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/fs/copy-paste.lua
- lua/nvim-tree/actions/fs/remove-file.lua
- lua/nvim-tree/actions/fs/trash.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/marks/bulk-delete.lua
- lua/nvim-tree/marks/bulk-trash.lua
This PR adds the optional `kind` parameter to the `vim.ui.select` function calls.
Having this parameter set to something will help in differentiating the `ui.select` prompts of `nvim-tree` from other sources (like LSP code actions or other plugins). This can help in more finer configurations at the user's end. As an example, with this setup I can configure `nvim-tree`'s select prompts to use the relative to cursor telescope theme, while all other prompts can follow the vertical dropdown telescope theme as default.
This does not create any changes in the UI. It only uses an optional parameter that is already present in the `vim.ui` API for this sort of finer configuration.
I'm open to changing/discussing the values I've used here. Something more generic (like `nvimtree_action`) or maybe …
> feat: add kind param to vim.ui.select function calls

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/colors.lua
- lua/nvim-tree/renderer/builder.lua
- lua/nvim-tree/renderer/init.lua
- lua/nvim-tree/view.lua
Create a combined highlight group when more than one, to work around the limitations of only two HL groups overriding each other.
TODO:
Define highlight groups in a namespace so that they may be removed.
The groups need to be added to the highlight group for the window via `nvim_win_set_hl_ns()`
This overrides view's `winhl` so those will need to be refactored in a similar manner.
This has questionable value.
> feat(#2415): combined hl groups

- lua/nvim-tree/lib.lua
- lua/nvim-tree/view.lua
> fix(#2624): open file from docked floating window

- lua/nvim-tree/appearance.lua
In the previous `colors.setup()` the highlight groups were setup using `hi def` but that was missing for those groups under `DEFAULT_DEFS`. 
I use catppuccin's `custom_highlights` to override `NvimTreeFolderIcon` and `NvimTreeWindowPicker`, which did not work in overriding the default highlights after the recently pushed commits.
> fix: use highlight default for DEFAULT_DEFS

- lua/nvim-tree.lua
- lua/nvim-tree/appearance.lua
- lua/nvim-tree/renderer/builder.lua
- lua/nvim-tree/renderer/components/full-name.lua
- lua/nvim-tree/renderer/init.lua
- lua/nvim-tree/view.lua
fixes #2643
fixes #2651
Reverts to `&winhl` instead of a highlight namespace for the nvim-tree window. See #2634 comments for details on issues encountered.
> fix(#2643): correctly apply linked highlight groups in tree window

- doc/nvim-tree-lua.txt
- lua/nvim-tree/appearance.lua
This is a break however it is needed. The normalised highlight groups brought them too close together.
Git groups could do with some disambiguation however there are no standards. We could bring them in line with gitsigns and lualine however that may be too much of a breaking change.
With default dark scheme:
- root: purple->bold purple (Title)
- modified: dark brown->green (Type)
- opened: dark brown->light brow (Special)
- bookmark icon: dark brown->folder icon 
- specials: ->blue undercurl (SpellCap)
Added more documentation.
> fix(#2415): disambiguate highlight groups, see :help nvim-tree-highlight-overhaul

- lua/nvim-tree/appearance.lua
Did not test clean room with indent markers enabled.
> fix(#2415): NvimTreeIndentMarker highlight group: FileIcon->FolderIcon

- doc/nvim-tree-lua.txt
- lua/nvim-tree/appearance.lua
- lua/nvim-tree/renderer/builder.lua
nvim-tree is using `nvim_get_hl` which was introduced in nvim 0.9 to replace the unstable `get_hl_defs` in the following [commit](https://github.com/neovim/neovim/pull/22693/files).
Unfortunately this raises an error in 0.8 nvim versions due to the function not existing.
```
Failed to run `config` for nvim-tree.lua
...are/nvim/lazy/nvim-tree.lua/lua/nvim-tree/appearance.lua:199: attempt to call field 'nvim_get_hl' (a nil value)
stacktrace:
- ~/.config/nvim/lua/confidenceman02/plugins/nvim-tree.lua:14 _in_ **config**
- ~/.config/nvim/lua/confidenceman02/lazy.lua:14
```
- Fall back to get_hl_defs when detecting 0.8
- Set the 'link' property to nil to emulate `link = false` in `builder.lua`
> fix(#2415): nvim 0.8 highlight overhaul support, limited to only show highest highlight precedence

- lua/nvim-tree/help.lua
magenta title got lost in the default magenta background
> fix(#2415): highlight help header and mappings

- .github/workflows/ci.yml
This PR updates CI workflow such that
- `push` is no longer triggering runs (we don't need to run it on master as it's guarded on PR level, release-please branch should also be triggered by `pull_request`)
- nvim version is no longer hardcoded but `stable` tag is used instead
- `nightly` is added to nvim versions matrix - this might prepare us for upcoming releases
- environment variables are set vie `env` key instead of inlining them
> ci: triggers, nvim stable version & env vars

- lua/nvim-tree.lua
Hi there, I encountered an error message generated by `vim.fn.searchcount` in `M.place_cursor_on_node` function when having `hijack_cursor` option enabled. 
I don't know if this fix is wanted or not, its just something that bothered me when using `vim.fn.searchcount` and I noticed it occurring when opening NvimTree.
Using `pcall` should fix the occurrence of the error message generated by `vim.fn.searchcount` as showing this error seems to be irrelevant to the `M.place_cursor_on_node` function:
```
E54: Unmatched (                                                                                                                                                    
Error detected while processing CursorMoved Autocommands for "NvimTree_*": …
```
> fix: searchcount exception on invalid search regex

- .github/workflows/ci.yml
- .github/workflows/release-please.yml
- .github/workflows/semantic-pr-subject.yml
This PR sets concurrency for all workflows and also runs ci workflow on master branch.
> ci: set concurrency and trigger ci on master

- lua/nvim-tree/appearance/init.lua
> fix(#2705): change NvimTreeWindowPicker cterm background from Cyan to more visible DarkBlue

- lua/nvim-tree/actions/fs/copy-paste.lua
Try to fix issue https://github.com/nvim-tree/nvim-tree.lua/issues/2535#issuecomment-2028457412 that I also encountered.
I write the data to a temporary buffer and use vim 'y' command to do real yank to trigger TextYankPost event with correct v:event.
> fix(#2535): TextYankPost event sends vim.v.event

- .github/workflows/luarocks.yml
Hey 👋
This PR is part of a push to get neovim plugins on [LuaRocks](https://luarocks.org/labels/neovim).
See also:
* [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim), a new luarocks-based plugin manager.
* [this blog post](https://mrcjkb.github.io/posts/2023-01-10-luarocks-tag-release.html).
With luarocks/rocks.nvim, it is [the plugin authors' responsibility to declare dependencies - not the user's](https://github.com/nvim-neorocks/rocks.nvim?tab=readme-ov-file#grey_question-why-rocksnvim). Installing this plugin is as simple as `:Rocks install nvim-tree.lua`.
* Add a workflow that publishes tags to luarocks.org when a tag or release is pushed.
> [!IMPORTANT]
> **For the luarocks workflow to work, someone with a luarocks.org account will have to add their [API …
> ci: luarocks releases

- lua/nvim-tree/explorer/node.lua
This PR fixes an infrequent (once every couple days), but annoying, nil access exception.
Occasionally, when switching git branches, to where some open files no longer existed, nvim-tree would raise a nil access exception, which would disable git integration until nvim was restarted. The stack trace brought me to this line.
I made this change a few weeks ago and have stopped seeing the error entirely, with no other changes to my local config. Seemed like a small enough fix to just contribute without any further research, as it's helped me on my local setup! Though, if you would prefer to dig into a root cause of why `status` was being passed as nil here, I would not be offended 😄
> fix: nil access exception with git integration when changing branches

- lua/nvim-tree/diagnostics.lua
According to [Neovims Release news](https://neovim.io/doc/user/deprecated.html) in the newly released v.0.10 `vim.diagnostic.is_disabled()` is deprecated in favor of `vim.diagnostic.is_enabled()`. 
I wasn't sure if there should be backwards compatibility left in for v0.9 or not. I'm not very solid with Lua, so I don't know if that `if/else` makes sense to 'solve' backwards compatibility.
> refactor: replace deprecated use of vim.diagnostic.is_disabled() 

- lua/nvim-tree/diagnostics.lua
This reverts commit 4215f33da55cf93163c5f429ec6f73af86be08c2.
#2781
> revert(#2781): "refactor: replace deprecated use of vim.diagnostic.is_disabled()"

- .luarc.json
- Makefile
- README.md
- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/finders/search-node.lua
- lua/nvim-tree/actions/node/open-file.lua
- lua/nvim-tree/appearance/diagnostics.lua
- lua/nvim-tree/appearance/init.lua
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/help.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/live-filter.lua
- lua/nvim-tree/renderer/builder.lua
- lua/nvim-tree/renderer/init.lua
- lua/nvim-tree/utils.lua
- lua/nvim-tree/view.lua
> chore(#2787): minimum nvim version 0.9, replace 0.10 deprecated, enable deprecated warnings

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/explorer/watch.lua
- lua/nvim-tree/git/init.lua
> feat(#2799): `filesystem_watchers.ignore_dirs` and `git.disable_for_dirs` may be functions

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/node/open-file.lua
fixes #2127
Try to fix #2127 and #2803
add `experimental.open.relative_path` option
> feat(#2127): add experimental.actions.open_file.relative_path to open files with a relative path rather than absolute

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/tree/init.lua
- lua/nvim-tree/actions/tree/resize.lua
- lua/nvim-tree/api.lua
- lua/nvim-tree/view.lua
Resolved #2598 
I slightly modified `useState` analogy to follow proposed API specification:
```lua
local resize = require("nvim-tree.api").tree.resize
local function use_nvim_tree_width(options)
if type(options) ~= "table" then
return
end
---@type number
local offset = options.offset
if type(offset) ~= "number" then
offset = 10
end
---@type number|table
local width = 30
local function get_width()
return width
end
local function increment_width()
resize({ relative = offset }) -- <==== here
end
local function decrement_width()
resize({ relative = -offset }) -- <==== here
end
local function dynamic_width()
width = {}
resize({ width = width }) -- <==== here
end
return get_width, increment_width, decrement_width, dynamic_width
end
```
Small showcase:
GIF explanation:
1. Increase
2. Increase …
> feat(#2598): add api.tree.resize

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/enum.lua
- lua/nvim-tree/renderer/builder.lua
- lua/nvim-tree/renderer/decorator/init.lua
- lua/nvim-tree/renderer/init.lua
Closes #2349
```lua
require('nvim-tree').setup {
renderer = {
icons = {
git_placement = 'right_align',
modified_placement = 'right_align',
diagnostics_placement = 'right_align',
bookmarks_placement = 'right_align',
padding = ' ',
show = {
file = true,
folder = true,
diagnostics = true,
bookmarks = true,
git = true,
modified = true,
},
},
},
}
```
If there's anything you'd like me to change about documentation or code, let me know, I'll do it.
> feat(#2349): add "right_align" option for renderer.icons.*_placement

- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/init.lua
- lua/nvim-tree/explorer/reload.lua
- lua/nvim-tree/explorer/sorters.lua
Implementation for https://github.com/nvim-tree/nvim-tree.lua/issues/2829
fixes #2829
> refactor(#2829): multi instance nvim-tree.explorer.sorters

- lua/nvim-tree/actions/node/open-file.lua
> fix(#2859): make sure window still exists when restoring options

- lua/nvim-tree/actions/moves/item.lua
- lua/nvim-tree/lib.lua
> fix(#2878): nowrapscan prevents move from root

- lua/nvim-tree/view.lua
> fix(#2879): remove unnecessary tree window width setting to prevent unnecessary :wincmd =

- lua/nvim-tree/actions/fs/remove-file.lua
- lua/nvim-tree/explorer/explore.lua
- lua/nvim-tree/explorer/init.lua
Added type fallback to make nvim-tree work with sshfs.
fixes #2794
> fix(#2794): sshfs compatibility

- lua/nvim-tree/explorer/explore.lua
FIx for https://github.com/nvim-tree/nvim-tree.lua/issues/2906
It looks like there are some situations where the explorer tries to populate a node when it is already populated. This leads to a situation in the code where the filter reason is none, however the node has already been loaded. This in turn leads to an attempt to record the hidden stats for the reason. Since the reason however is none and the `hidden_stats `object has understandably not been initialised to capture stats for reason none, the following exception is thrown
```txt
Error executing vim.schedule lua callback: ...r/start/nvim-tree.lua/lua/nvim-tree/explorer/explore.lua:69: attempt to perform
arithmetic on a nil value
...r/start/nvim-tree.lua/lua/nvim-tree/explorer/explore.lua:69: in function …
```
> fix(#2906): resource leak on populate children

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/node/system-open.lua
> feat(#2430): use vim.ui.open as default system_open, for neovim 0.10+

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/fs/clipboard.lua
fixes #2917 
Continued the `".."` testing pattern, #2886 should boil these conditions away.
> fix(#2917): fix root copy paths: Y, ge, gy, y

- lua/nvim-tree/lib.lua
The return value of `core.get_explorer()` could be changed by the `core.init(..)` between the binding (L266) and its later uses (L281 onwards): 
https://github.com/nvim-tree/nvim-tree.lua/blob/8405ecfbd6bb08a94ffc9c68fef211eea56e8a3b/lua/nvim-tree/lib.lua#L266-L284
> fix: invalid explorer on open

- lua/nvim-tree/actions/node/open-file.lua
> fix(#2951): highlights incorrect following cancelled pick

- lua/nvim-tree/actions/node/open-file.lua
- lua/nvim-tree/utils.lua
Description
With this change (https://github.com/nvim-tree/nvim-tree.lua/commit/45a93d99794fff3064141d5b3a50db98ce352697#diff-eeb21711fceb0abba1450bd1adcbecc4fd90cf8ce4d5d7a8233f886c1bebd41fR375), I found it doesn't work well on Windows for 2 cases:
1. When I open a file from nvim-tree, the root of nvim-tree window changed to the directory of that file
2. The buffer of this file can not be listed when I use telescope command `<cmd>lua require('telescope.builtin').buffers(require('telescope.themes').get_dropdown{previewer = false})<cr>
Neovim version`
This PR is to revert the change and fix the issue #2961 and #2862
> fix(#2961): windows: escape brackets and parentheses when opening file

- lua/nvim-tree/actions/fs/rename-file.lua
Use the full path, as used in rename(), for the subsequent call to find_file(), in order to correctly re-select the renamed item.
Fix for 
https://github.com/nvim-tree/nvim-tree.lua/issues/2969
> fix(#2969): After a rename, the node loses selection

- lua/nvim-tree/explorer/init.lua
> fix(#2976): use vim.loop to preserve neovim 0.9 compatibility

- lua/nvim-tree/node/directory.lua
> fix(#2978): grouped folder not showing closed icon

- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/view.lua
> fix(#2954): resolve occasional tree flashing on diagnostics, set tree buffer options in deterministic order

- lua/nvim-tree/utils.lua
> fix(#2981): windows: root changed when navigating with LSP

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/node/open-file.lua
> feat(#2819): add actions.open_file.relative_path, default enabled, following successful experiment

- lua/nvim-tree/diagnostics.lua
This ensures that LSP diagnostics of files which are not manually opened by users are rendered by nvim-tree diagnostic indicators.
However when users attach an LSP to nvim-tree this will bring back flashing as attempted to fix in #2980. Fixing this should probably done by checking data passed via diagnostic events (DiagnosticChanged and CocDiagnosticChanged).
> fix(#2990): Do not check if buffer is buflisted in diagnostics.update()

- lua/nvim-tree/api.lua
The `wrap_node` and `wrap_node_or_nil` functions now correctly accept `Node?` to handle nil values, resolving a warning about incorrect argument counts in `api.tree.change_root_to_node()`.
> fix(api): correct argument types in `wrap_node` and `wrap_node_or_nil`

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/diagnostics.lua
fixes #2954 
@des-b I'd be most grateful for your review and thoughts.
This changes the approach to LSP:
* examine the `DiagnosticChanged` data on the event (sync) thread
* `NODE_SEVERITIES` and `NODE_SEVERITIES_VERSION` only updated on delta
* on delta a redraw is scheduled
The debounce delay was increased as there are a _lot_ of events as the user types.
It's not clear whether a full redraw `R` is needed; it could clear `NODE_SEVERITIES` and rebuild it. YAGNI?
> fix(#2954): more efficient LSP updates, increase diagnostics.debounce_delay from 50ms to 500ms

- lua/nvim-tree/view.lua
> fix(#3009): nvim < 0.10 apply view options locally

- lua/nvim-tree/actions/root/change-dir.lua
- lua/nvim-tree/watcher.lua
> docs: notify users with a fs.inotify.max_user_watches message on EMFILE event

- lua/nvim-tree/view.lua
Fixes https://github.com/nvim-tree/nvim-tree.lua/issues/3015
> fix(#3015): dynamic width no longer truncates on right_align icons

- lua/nvim-tree/diagnostics.lua
> fix(#3041): use vim.diagnostic.get for updating diagnostics

- lua/nvim-tree.lua
I have some autocmds on `DirChanged` to record my directory history.
Currently, with `hijack_directories` enabled, `gf` or `:e /some/dir` will jump to directory without triggering the `DirChanged` events.
> fix: hijack directory "BufEnter", "BufNewFile" events are nested

- lua/nvim-tree/actions/node/file-popup.lua
- lua/nvim-tree/renderer/components/full-name.lua
Fixes https://github.com/nvim-tree/nvim-tree.lua/issues/3045
This PR fixes the issue of the [Scratch]-Buffer remaining after closing `full-name.lua::show()` and `require("nvim-tree.api").node.show_info_popup()`. Since I’m not sure if it covers all cases, I will add any missing parts in a timely manner. Wishing you have a great day.
Best regards !
> fix(#3045): wipe scratch buffers for full name and show info popups

- lua/nvim-tree/explorer/init.lua
When opening neovim in a directory with a git repo for the first time after PC reboot, I always got this error message:
```
Fehler beim Ausführen von "BufEnter Autokommandos für "*"":
Error executing lua callback: ...-data/lazy/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:395: attempt to perform arithmetic on a nil value
...-data/lazy/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:395: in function 'populate_children'
...-data/lazy/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:419: in function 'explore'
...-data/lazy/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:328: in function '_load'
...-data/lazy/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:70: in function 'new'
...l/nvim-data/lazy/nvim-tree.lua/lua/nvim-tree/classic.lua:82: in function …
```
> fix: arithmetic on nil value error on first git project open

- doc/nvim-tree-lua.txt
- lua/nvim-tree/api.lua
- lua/nvim-tree/view.lua
fixes #1984
As discussed on #1984 , this should implement the ability of specifying the following two options in the `api.node.open.edit` method:
- `quit_on_open`: if set to true, it closes the tree when file related to the node is opened;
- `focus`: if set to ~~true~~ false, opens the file but keep the focus on the tree. Similar to what's done in the preview feature, but actually creating a new buffer for each file.
For now I've added a draft commit that supports the first option and then just checks it and closes the tree view in the edit API method.
Not sure if that's the best option, but at first I decided to not forward it to the action level to not mix it with the `quit_on_open` global option that can be passed in to the action, and also to keep the changes restricted to the API …
> feat(#1984): add quit_on_open and focus opts to various api.node.open functions

- lua/nvim-tree/actions/node/open-file.lua
This addresses a minor issue that I have with the window picker — if `stl` and/or `stlnc` `fillchars` are set, they are not hidden when the picker is shown:
This example uses the replication from [here](https://github.com/nvim-tree/nvim-tree.lua/wiki/Troubleshooting#clean-room-replication) together with `:set fillchars+=stl:*,stlnc:*`:
The selection characters are hard to spot and hidden. This PR addresses this problem by temporarily disabling these characters when the window picker is displayed.
> fix: window picker: hide fillchars: stl and stlnc

- .editorconfig
- .github/workflows/ci.yml
- .luarc.json
- CONTRIBUTING.md
- Makefile
- lua/nvim-tree/explorer/init.lua
- scripts/luals-check.sh
update versions:
* luacheck 1.1.1 -> 1.2.0
* luarocks v4 -> v5
* lua-language-server 3.11.0 -> 3.13.9
Small ci.yml tweaks.
Use the embedded EmmyLuaCodeStyle `CodeFormat` when checking style. This makes it easier for those who don't have it installed, as well as simlifying CI.
`CodeFormat` binary is still required for fixing style; doc updated.
Contentious change: style job collapsed into check, as they have all prerequisites in common.
TODO: update required checks following merge
> chore: use builtin EmmyLuaCodeStyle for style checking

- lua/nvim-tree/renderer/components/full-name.lua
This fixes the following problem in `nvim` `v0.11.0` onwards, when `winborder` settings is used:
`nvt-min.lua`:
```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvt-min/site]])
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
require("packer").startup({
{
"wbthomason/packer.nvim",
"nvim-tree/nvim-tree.lua",
"nvim-tree/nvim-web-devicons",
-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
},
config = {
package_root = package_root,
compile_path = install_path .. "/plugin/packer_compiled.lua",
display = { non_interactive = true },
},
})
end
if vim.fn.isdirectory(install_path) == 0 then
print("Installing nvim-tree …
```
> fix: explicitly set `border` to `"none"` in full name float

- lua/nvim-tree/explorer/init.lua
> fix(#3101): when renderer.highlight_opened_files = "none" do not reload on BufUnload and BufReadPost

- lua/nvim-tree.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/view.lua
Fixes `TreeOpen` and `TreeClose` event dispatch, per this discussion: https://github.com/nvim-tree/nvim-tree.lua/pull/3105#issuecomment-2807238355. Post this, both these events should only be dispatched exactly once in every case.
Just to note, for `TreeClose`, I found out while implementing that autocmd on `WinClosed` does not match with the file name. Instead it matches with the window ID, which we would not know (I think?).
So instead, I had to write it as a condition in the callback to check the filetype of the underlying buffer to be `NvimTree`. Do let me know if anything can be improved here.
Any other thoughts on this ? @alex-courtis 
Thanks!
> fix: reliably dispatch exactly one TreeOpen and TreeClose events

- doc/nvim-tree-lua.txt
- lua/nvim-tree/events.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/view.lua
This adds 2 new events `TreePreOpen` and `TreePreClose`, which get triggered before `TreeOpen` and `TreeClose` events. They work similar to `TreeOpen` and `TreeClose`, in terms of the handler function.
This should help running logic **before** the NvimTree window is created or removed.
Let me know your thoughts.
Thanks!
> feat: add TreePreOpen event

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/legacy.lua
- lua/nvim-tree/renderer/builder.lua
- lua/nvim-tree/renderer/components/padding.lua
resolves #3113 
default: opts.renderer.icons.folder_arrow_padding = " "
> feat(#3113): add renderer.icons.folder_arrow_padding

- lua/nvim-tree/utils.lua
> fix(#3122): remove redundant vim.validate

- lua/nvim-tree/renderer/builder.lua
fixes #3124 
Bug is caused in `builder.lua`:
```lua
for _, d in ipairs(self.decorators) do
add_to_end(rights, d:icons_right_align(not d:is(UserDecorator) and node or api_node))
end
```
In the case of tracked dotfiles, `d:icons_right_align(not d:is(UserDecorator) and node or api_node)` returns `{}` from the HiddenDecorator, but inside `add_to_end(t1, t2)` we only check `if not t2`. Not sure if this was intentional, I didn't notice any unexpected behaviour while testing but there may be edge cases I hadn't thought of.
> fix(#3124): fix icon padding for "right_align" placements, notably for dotfiles

- lua/nvim-tree.lua
Hello there,
I got the following error if I try to close the [mcphub.nvim](https://github.com/ravitemer/mcphub.nvim) window with q. This fixes this error:
> fix: "Invalid buffer id" on closing nvim-tree window

- lua/nvim-tree/renderer/components/full-name.lua
- lua/nvim-tree/utils.lua
- lua/nvim-tree/view.lua
Closes https://github.com/nvim-tree/nvim-tree.lua/issues/2746
Also I added functionality for copying over right-aligned icons to the float.
Before:
After:
> fix(#2746): background and right aligned icons in floating windows

- doc/nvim-tree-lua.txt
- lua/nvim-tree/actions/node/open-file.lua
This PR ensures that when using `open.no_window_picker`, the fallback window selection respects the `window_picker.exclude` configuration.
Previously, if no window picker was used, nvim-tree would open the file in the last active window, even if that window matched an excluded type (e.g., a terminal).
Now it sets the fallback window as the first available usable window, not excluded in the configuration, which can prevent undesired behavior.
Fixes #3143
I removed the `first_win_id` function to avoid redundant calls to `usable_win_ids`. Happy to adjust if you'd like to keep it.
Let me know if there’s any other adjustment or further cleanup you’d like.
Appreciate your time and review!
> fix(#3143): actions.open_file.window_picker.exclude applies when not using window picker

- lua/nvim-tree/actions/node/open-file.lua
Hidden win should never be used as target.
Use neovim nightly
```lua
for name, url in pairs {
nvt = 'https://github.com/nvim-tree/nvim-tree.lua',
} do
local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
if vim.fn.isdirectory(install_path) == 0 then
vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
end
vim.opt.runtimepath:append(install_path)
end
require('nvim-tree').setup {}
require('vim._extui').enable({})
```
```sh
nvim --clean -u nvim-tree-hide.lua +"%bd!" +NvimTreeOpen
```
> fix: window picker ignore hidden window

- lua/nvim-tree/actions/node/file-popup.lua
Hi, this solves an error when the info window is closed via `fclose` - `vim.cmd("fclose")`. I have this in a keymap bind to `ESC` and get this error: 
```
x Error  12:13:38 msg_show.lua_error Error detected while processing CursorMoved Autocommands for "*":
Error executing lua callback: .../nvim-tree.lua/lua/nvim-tree/actions/node/file-popup.lua:60: Invalid window id: 1004
[C]: in function 'nvim_win_close'
.../nvim-tree.lua/lua/nvim-tree/actions/node/file-popup.lua:60: in function <.../nvim-tree.lua/lua/nvim-tree/actions/node/file-popup.lua:58>
```
The fix is to check if window id is still valid.
> fix: invalid window id for popup info window

- doc/nvim-tree-lua.txt
wiki to be updated following merge
> docs: polish example decorator

- lua/nvim-tree/actions/fs/remove-file.lua
Fixed issue #3077 
The problem was that nvim-tree did not check if the file was a symlink, and the method `vim.loop.fs_stat(cwd)` returns the filetype of the file that the symlink points to, not the type of file the symlink is. I simply added a check `vim.loop.fs_lstat(new_cwd)`, which returns an object with type == "link" if the file is a symlink.
> fix(#3077): deleting a directory containing symlinked directory will delete the contents of the linked directory

- lua/nvim-tree/explorer/view.lua
- lua/nvim-tree/globals.lua
Behind (default off) feature gate `experimental.close_other_windows_in_tab`
> feat(#2826): allow only one window with nvim-tree buffer per tab

- doc/nvim-tree-lua.txt
- lua/nvim-tree.lua
- lua/nvim-tree/actions/fs/remove-file.lua
- lua/nvim-tree/actions/node/open-file.lua
- lua/nvim-tree/actions/root/change-dir.lua
- lua/nvim-tree/actions/tree/toggle.lua
- lua/nvim-tree/api.lua
- lua/nvim-tree/core.lua
- lua/nvim-tree/diagnostics.lua
- lua/nvim-tree/explorer/init.lua
- lua/nvim-tree/explorer/live-filter.lua
- lua/nvim-tree/explorer/view.lua
- lua/nvim-tree/globals.lua
- lua/nvim-tree/lib.lua
- lua/nvim-tree/multi-instance-debug.lua
- lua/nvim-tree/renderer/init.lua
fixes #3180 
fixes #3177 
Reverts recent view changes:
* buffer autocommands for wipeout
* experiment #3174 
* changing `globals.TABPAGES` to a simple map
Consistency check removal to follow, proof of concept was not successful.
> revert(#3180, #3177): invalid group or tabpage

- lua/nvim-tree/git/init.lua
toplevel for untracked was not cached in the getter `git.get_toplevel`
Only cached by one caller `git.load_project`, however I'm hesitant to remove it from this complex module, and it does no harm.
> perf(#3171): cache toplevel for untracked

- lua/nvim-tree/legacy.lua
- lua/nvim-tree/utils.lua
fixes #3196 
* remove `utils.read_file`
* move `utils.move_missing_val` and `table_create_missing` to legacy as it is the only consumer
No other obvious removals / refactors stood out.
> chore(#3196): remove unused utils and refactor

- lua/nvim-tree/actions/finders/find-file.lua
- lua/nvim-tree/actions/moves/item.lua
- lua/nvim-tree/actions/moves/parent.lua
- lua/nvim-tree/actions/moves/sibling.lua
- lua/nvim-tree/actions/tree/modifiers/collapse.lua
- lua/nvim-tree/explorer/filters.lua
- lua/nvim-tree/explorer/init.lua
- lua/nvim-tree/explorer/live-filter.lua
- lua/nvim-tree/git/init.lua
- lua/nvim-tree/marks/init.lua
- lua/nvim-tree/utils.lua
> refactor(#2942): multi instance: move utils functions to Explorer methods
